<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What is channel, , s name)_Inp_00fae1</name>
   <tag></tag>
   <elementGuidId>9cec7537-dffe-4f27-aaaa-727d2dfe6f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47b6d68a-620b-4af4-a6d4-e9d78da41c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]</value>
      <webElementGuid>c436919c-707f-439d-a530-6a69ff1b0cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the channel's name</value>
      <webElementGuid>ddff2c40-1d14-42b5-b6d2-be77dbcc0a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;w-[100vw] h-[100vh] overflow-hidden fixed top-0 left-0 z-50 bg-black bg-opacity-80 flex flex-row justify-center items-center&quot;]/div[@class=&quot;z-60 w-full h-full sm:w-4/5 sm:max-h-[570px] md:w-[684px] bg-bgPrimary rounded-2xl flex-col justify-start  items-start gap-3 inline-flex&quot;]/div[@class=&quot;self-stretch md:h-96 flex-col justify-start items-start flex&quot;]/div[@class=&quot;self-stretch md:h-96 px-5 pt-8 flex-col justify-start items-start gap-3 flex&quot;]/div[@class=&quot;Frame408 self-stretch h-[84px] flex-col justify-start items-start gap-2 flex mt-1&quot;]/div[@class=&quot;ContentContainer self-stretch h-11 flex-col items-start flex&quot;]/div[@class=&quot;InputContainer self-stretch h-11 px-4 py-3 bg-neutral-950 rounded shadow border w-full border-blue-600  justify-start items-center gap-2 inline-flex&quot;]/div[@class=&quot;InputValue grow shrink basis-0 self-stretch justify-start items-center flex&quot;]/input[@class=&quot;Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]&quot;]</value>
      <webElementGuid>14131057-4548-411f-b43c-06f343a3bff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>fccac975-12e6-49bb-bd70-f152163fe286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>55f88d83-481d-4022-9620-320c0552f5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = concat(&quot;Enter the channel&quot; , &quot;'&quot; , &quot;s name&quot;)]</value>
      <webElementGuid>938ba896-8733-442e-9258-b39f01ddeb3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
