<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CLAN NAME_darkbg-bgTertiary bg-F0F0F0_55ae1b</name>
   <tag></tag>
   <elementGuidId>aad4dee7-0fc0-4647-b8e1-8bad8a0a1df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39f29ff1-5e41-42ed-a919-a75db8505e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99b909dc-74bc-4017-a5a3-3429fe2e795f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-bgTertiary bg-[#F0F0F0] font-[400]  px-[16px] rounded w-full dark:text-white text-black outline-none dark:bg-bgSurface bg-bgModifierHoverLight mb-2 mt-4 py-2</value>
      <webElementGuid>db5581fe-4dc4-4fc5-b571-f4414aba831a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>geBXclVQui's clan</value>
      <webElementGuid>8fc46b0a-20dc-494c-bff8-97d1a85b5250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark wf-ggsans-n4-active wf-active mdl-js&quot;]/body[1]/div[@class=&quot;justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none bg-black bg-opacity-80 dark:text-white text-black&quot;]/div[@class=&quot;relative w-full max-w-[684px] sm:h-auto h-full&quot;]/div[@class=&quot;border-0 rounded-lg shadow-lg relative flex flex-col w-full dark:bg-bgPrimary bg-bgLightModeSecond  outline-none focus:outline-none h-full sm:h-auto&quot;]/div[@class=&quot;relative px-5 py-4 flex-auto bg-transparent&quot;]/div[@class=&quot;dark:bg-[#323232] bg-bgLightModeSecond rounded-[5px] bg-transparent&quot;]/div[@class=&quot;flex items-center flex-col justify-center&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;dark:bg-bgTertiary bg-[#F0F0F0] font-[400]  px-[16px] rounded w-full dark:text-white text-black outline-none dark:bg-bgSurface bg-bgModifierHoverLight mb-2 mt-4 py-2&quot;]</value>
      <webElementGuid>470add3e-b16c-4f46-a677-45843bc60d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>72a0fb8f-51c9-46cf-beef-26deaf99ede8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>0b671d40-a3b9-4a49-b0d6-76f68c2ebf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = concat(&quot;geBXclVQui&quot; , &quot;'&quot; , &quot;s clan&quot;)]</value>
      <webElementGuid>5ab4b9d0-8980-43b4-9ec4-7940bb86fa15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
