<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>c435fb1d-cbb7-4dd0-9e42-27a580cecb88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Your Server'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>186bf0ac-f24d-4bf4-8f6b-88d778cca1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>59090f25-d51d-4037-9919-ff83ad6c3142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>768d78fb-7b23-4a5e-838e-01378e338824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 28 28</value>
      <webElementGuid>fccf7663-6bfe-4e2f-9597-c8bc65948214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>988326e8-8b27-4fb1-a290-d97c5d072ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e019401c-de8d-42fb-bf14-cab9cf4e2057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-ggsans-n4-active wf-active mdl-js&quot;]/body[1]/div[@class=&quot;justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none bg-black bg-opacity-80 text-white&quot;]/div[@class=&quot;relative w-full max-w-[684px] sm:h-auto h-full&quot;]/div[@class=&quot;border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-bgPrimary outline-none focus:outline-none h-full sm:h-auto&quot;]/div[@class=&quot;relative px-5 py-4 flex-auto bg-transparent&quot;]/div[@class=&quot;bg-[#323232] ounded-[5px] bg-transparent&quot;]/div[@class=&quot;flex items-center flex-col justify-center&quot;]/label[@class=&quot;block mt-8 mb-4&quot;]/div[@id=&quot;preview_img&quot;]/div[@class=&quot;absolute right-0 top-[-3px] left-[54px]&quot;]/svg[1]</value>
      <webElementGuid>8a6a4470-62d0-4f88-a45a-1eaa0d7dcda6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Your Server'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>cd6d0176-f933-4163-a1f1-715bcb65de55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e7c22449-7c2c-46d0-96d7-337a7d6960cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>57b563bd-05cf-4b2a-8ee7-8fb33caa376b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAN NAME'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>2de201b2-7fe8-4e52-a47c-e5d36752784b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
