<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_wellcome</name>
   <tag></tag>
   <elementGuidId>06939491-b282-4142-ab33-de66c5631390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editorReactMention</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editorReactMention']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>271f69fa-0175-4d89-a2ee-fad0942f7a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>54240eef-bada-40b3-9332-101d9ba06082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughs here...</value>
      <webElementGuid>243dbe74-3c79-4ecb-a0a7-0e4f48975650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>393ba4a6-cca2-4bf2-9357-d422d9367f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>wellcome</value>
      <webElementGuid>e5098866-ee86-40ae-93bc-3294505ccb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorReactMention&quot;)</value>
      <webElementGuid>ad6f1336-1d03-436b-98bd-a45e4a15fd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editorReactMention']</value>
      <webElementGuid>454e7238-756c-45bb-b6db-242b130406ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/textarea</value>
      <webElementGuid>e394b2fc-ed1f-4973-97fb-3c7e508aa150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wellcome'])[1]/following::textarea[1]</value>
      <webElementGuid>7a684dc6-a782-425a-bf96-2a3140e55cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned Messages'])[1]/following::textarea[1]</value>
      <webElementGuid>16b4aee0-13f2-4550-b011-48ea40c12c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[2]/preceding::textarea[1]</value>
      <webElementGuid>b5e40f16-6a7d-421b-8740-a97c43f93771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'scrollLoading', '&quot;', ')')])[1]/preceding::textarea[1]</value>
      <webElementGuid>5e2e7241-16c8-4175-a3cd-09348b3d9595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>91b7d83f-bfc5-475d-ab61-00b40b1f0bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughs here...' and (text() = 'wellcome' or . = 'wellcome')]</value>
      <webElementGuid>d548805a-fc35-4344-8211-a22bab4ed735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
