<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S dng mt ti khon khc</name>
   <tag></tag>
   <elementGuidId>e8b25af5-0473-4d45-868d-88649473e005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/div/div/div[2]/div/div/div[2]/div/div/div/form/span/section/div/div/div/div/ul/li[2]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.AsY17b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75b96ed3-d48d-4d76-9f8e-795b6b056eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AsY17b</value>
      <webElementGuid>ef1c0ad3-8711-4804-a0e6-2c13797ad89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sử dụng một tài khoản khác</value>
      <webElementGuid>3a3c64c5-964d-45a8-8a8e-56f650699d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/div[@class=&quot;gfM9Zd&quot;]/div[@class=&quot;tTmh9  NQ5OL&quot;]/div[@class=&quot;SQNfcc WbALBb&quot;]/div[@class=&quot;nR49Bf&quot;]/div[@class=&quot;PIEwGd&quot;]/div[@class=&quot;Anixxd&quot;]/div[@class=&quot;TFSJ7e&quot;]/div[@class=&quot;DdzYHd&quot;]/div[@class=&quot;HvrJge&quot;]/form[1]/span[1]/section[@class=&quot;Em2Ord&quot;]/div[@class=&quot;yTaH4c&quot;]/div[1]/div[@class=&quot;A0AdH&quot;]/div[@class=&quot;r4WGQb&quot;]/ul[@class=&quot;Dl08I&quot;]/li[@class=&quot;aZvCDf B682ne W7Aapd zpCp3 SmR8&quot;]/div[@class=&quot;VV3oRb YZVTmd SmR8&quot;]/div[@class=&quot;jbiPi&quot;]/div[@class=&quot;AsY17b&quot;]</value>
      <webElementGuid>1dd58b34-1f5b-4655-a227-dee933548f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/div/div/div[2]/div/div/div[2]/div/div/div/form/span/section/div/div/div/div/ul/li[2]/div/div/div[2]</value>
      <webElementGuid>472ed15a-5cb5-4ffe-851c-20e82a5a53d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nguyenthinga270702@gmail.com'])[1]/following::div[5]</value>
      <webElementGuid>a5c2de3f-93d1-421b-b801-8eb482a3bc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nga'])[1]/following::div[6]</value>
      <webElementGuid>49d57a08-716c-443d-93df-96475f4923e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‪Tiếng Việt‬'])[1]/preceding::div[8]</value>
      <webElementGuid>a37b9bfc-18d9-4283-aab0-c71660fa9fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‪Afrikaans‬'])[1]/preceding::div[10]</value>
      <webElementGuid>63ba71af-3dd3-4e99-accc-8ca77c9171d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sử dụng một tài khoản khác']/parent::*</value>
      <webElementGuid>fb7e8720-5d84-482f-9be5-2a28e9134152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]</value>
      <webElementGuid>f8466a7c-ba9a-4704-90cc-2b42ced88dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sử dụng một tài khoản khác' or . = 'Sử dụng một tài khoản khác')]</value>
      <webElementGuid>9257f31c-f8dd-4e85-bdd1-6c280bae6e77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
