<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_emoji</name>
   <tag></tag>
   <elementGuidId>20cd1b94-2ae3-47bc-9416-12c38f3ee082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-layout&quot;]/div/div[3]/div[2]/div[1]/div[2]/div[2]/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div/div/button[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
