<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reaction_pannel</name>
   <tag></tag>
   <elementGuidId>45c9f96b-b4af-4011-8737-a44a0c178cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.h-full.p-1.cursor-pointer.popup-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;scrollLoading&quot;]/div[2]/div/div[@data-index][last()]/div[1]/div/div[2]/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82c2436f-b12e-4db5-845b-416450cf781c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full p-1 cursor-pointer popup-btn</value>
      <webElementGuid>d64604be-bee6-4d0b-b73d-d8c45f6f5c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollLoading&quot;)/div[2]/div[1]/div[14]/div[@class=&quot;fullBoxText relative group pt-3&quot;]/div[1]/div[@class=&quot;chooseForText z-[1] absolute h-8 p-0.5 rounded block -top-5  right-6 w-fit&quot;]/div[@class=&quot;flex justify-between dark:bg-bgDarkPopover bg-bgLightMode border border-bgSecondary rounded&quot;]/div[@class=&quot;w-fit h-full flex items-center justify-between&quot;]/button[@class=&quot;h-full p-1 cursor-pointer popup-btn&quot;]</value>
      <webElementGuid>a755ba3d-4abe-418f-8374-05ff3cef0c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollLoading']/div[2]/div/div[14]/div/div/div[2]/div/div/button</value>
      <webElementGuid>4826ae81-fea7-4971-a12a-c1e8ef86c718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toi la bot'])[5]/following::button[1]</value>
      <webElementGuid>b747be36-4a43-404c-98f2-02608a4bdf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today at 09:44'])[3]/following::button[1]</value>
      <webElementGuid>2a3525c1-2cdc-45ec-b79b-26c5f1de5309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/button</value>
      <webElementGuid>eeaf3a3b-a6da-4bf4-8b79-deb8188c7c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
