<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_latest message</name>
   <tag></tag>
   <elementGuidId>45e56040-47a7-4141-a24b-9dfa6905b65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;scrollLoading&quot;]/div[2]/div/div[@data-index][last()]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b482ded4-bc9f-45e5-b1c3-1309783e26ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-15 flex-col w-auto px-3 dark:bg-[#403D38] bg-[#EAB3081A]</value>
      <webElementGuid>0d1d25d0-551f-4e11-a582-766f41f80dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>geBXclVQui he lo mngeBXclVQuiToday at 09:44toi la bot</value>
      <webElementGuid>0678ba55-3c33-4055-8755-d0806f515b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-1840651253101629440&quot;)/div[@class=&quot;relative rounded-sm overflow-visible&quot;]/div[@class=&quot;flex h-15 flex-col w-auto px-3 dark:bg-[#403D38] bg-[#EAB3081A]&quot;]</value>
      <webElementGuid>5e679e23-021e-46e2-8540-2bba7bb9841c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg-1840651253101629440']/div/div[2]</value>
      <webElementGuid>a0d3a5ca-d25b-4def-9df7-5e1d0f708514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='he lo mn'])[13]/following::div[10]</value>
      <webElementGuid>142d27fe-6b60-4a60-b31d-0efc07574b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toi la bot'])[4]/following::div[30]</value>
      <webElementGuid>6f5f7bac-258b-43e6-baac-f7f602dc4e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div/div[2]</value>
      <webElementGuid>38b4bcba-747e-4619-b6e5-95963ea72184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'geBXclVQui he lo mngeBXclVQuiToday at 09:44toi la bot' or . = 'geBXclVQui he lo mngeBXclVQuiToday at 09:44toi la bot')]</value>
      <webElementGuid>c220d0fd-1dcc-4ceb-a9e2-b18adeb6a1a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
