<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_channel T</name>
   <tag></tag>
   <elementGuidId>d95c3a12-a9b0-4c0a-befb-351bf831a297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editorReactMention</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editorReactMention']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>83276ea9-cff4-4abc-8461-bcdfda70e05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>7a7bf78a-01a9-4d14-a04b-60552dae82a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughts here...</value>
      <webElementGuid>6cb80841-a9f1-4a97-a766-578dd545b037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>96767d13-0dbf-46bb-ad0f-af9f15cd6aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorReactMention&quot;)</value>
      <webElementGuid>a70b6841-8e42-418d-bd03-4a522ffa19a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editorReactMention']</value>
      <webElementGuid>06d6ae61-371f-48bd-a4a2-5ee4bc48c11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div[2]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>a8c188c2-cc3f-4a28-851d-fb5cfb13ef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>aac9a1cc-d13a-402a-a4c0-f126964ccccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughts here...']</value>
      <webElementGuid>0ccbd55b-3a15-441e-b931-67f7a3d1ebf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
