<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DM_w-fit</name>
   <tag></tag>
   <elementGuidId>1a253aed-826f-4ba9-86f9-e54ba88aa279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/a/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.w-fit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8543ba5-635e-4057-bc17-d0a5176b703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit</value>
      <webElementGuid>24983d59-42bc-446b-8d98-8e7abd16238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>flowbite-tooltip-target</value>
      <webElementGuid>442db596-0874-4b0b-bc3f-74f8eb196a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1o:</value>
      <webElementGuid>ed080e73-d203-48d3-8740-8856600f9cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/a[1]/div[@class=&quot;group block relative rounded-3xl&quot;]/div[@class=&quot;group-active:translate-y-px&quot;]/div[@class=&quot;w-fit&quot;]</value>
      <webElementGuid>1f5e0f90-4cbd-483b-b437-90cbf896fe67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/a/div/div[2]/div</value>
      <webElementGuid>cc1c43ec-12ba-4e91-90d9-df59e7fe36bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM'])[1]/preceding::div[3]</value>
      <webElementGuid>e2181193-a147-46ba-b533-d61891abf0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test-create-a_Clan'])[1]/preceding::div[11]</value>
      <webElementGuid>b54c7a38-2bf4-4b6c-a1ed-1c8acbbc2f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/div</value>
      <webElementGuid>a616eaa2-2510-4058-ad53-1c181fe99882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
