<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Members</name>
   <tag></tag>
   <elementGuidId>0d4113bd-a65a-496f-b96b-5a17c4c5d051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div/a/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bb1f20c-a87c-4874-a158-84797c58ed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[99px] dark:text-zinc-400 text-colorTextLightMode text-base font-medium</value>
      <webElementGuid>f0de861a-c5db-4ab2-9553-05be4ea6fdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>f34a9272-55bd-46c2-96ed-97876e1d50f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;self-stretch h-fit flex-col justify-start items-start gap-1 p-2 flex&quot;]/a[@class=&quot;self-stretch inline-flex cursor-pointer px-2 rounded h-[34px]  dark:hover:bg-bgModifierHover hover:bg-bgModifierHoverLight&quot;]/div[@class=&quot;grow w-5 flex-row items-center gap-2 flex&quot;]/div[@class=&quot;w-[99px] dark:text-zinc-400 text-colorTextLightMode text-base font-medium&quot;]</value>
      <webElementGuid>b17e962c-baf6-48ff-95b0-3f1fd647cdef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div/a/div/div[2]</value>
      <webElementGuid>822b1ed8-a922-4c52-9fcf-70a4c7fc0db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test-create-a_Clan'])[1]/following::div[23]</value>
      <webElementGuid>2495d9d1-cb85-4c90-b265-c7ef21ab722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM'])[1]/following::div[33]</value>
      <webElementGuid>dea6a854-65ed-46a4-8625-8233cc94cdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/preceding::div[1]</value>
      <webElementGuid>0dcd7adf-e74a-432e-9ef9-e294dd7f9929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::div[4]</value>
      <webElementGuid>0f482e29-d951-45a0-ac3c-8c886f1157ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Members']/parent::*</value>
      <webElementGuid>31c35291-aec2-4f0e-b395-652b71f5ece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/div/div[2]</value>
      <webElementGuid>cd483849-0bad-41c5-8af5-4c927c943406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Members' or . = 'Members')]</value>
      <webElementGuid>9f2d78e0-5a7b-4ae6-88fa-2ac5c9c34cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
