<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidebar1</name>
   <tag></tag>
   <elementGuidId>8af33f38-4096-44d3-916f-4151ab9488b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cursor-pointer w-[272px] p-3 left-0 top-0 absolute flex h-heightHeader justify-between items-center gap-2 dark:bg-bgSecondary bg-bgLightMode dark:hover:bg-[#35373C] hover:bg-[#E2E7F6] shadow border-b-[1px] dark:border-bgTertiary border-white']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c279dea6-96a7-4b15-a682-31154331d75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8956e7a7-0db7-4481-b94e-7ed325446a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5076ca4-02af-42c8-a148-2debfa9d1af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3224b9b4-cd9f-4e1c-a9b2-356f53516d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a5730e5-452a-460a-93e9-118928d8125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>08a5ba7f-339c-4780-a4c4-fc479415bdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2019097f-b5c7-4571-af61-dd3610bd1232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>c1339c1e-a6e3-4eb2-a432-ce5ad1a42224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:hover:text-white hover:text-black dark:text-[#B5BAC1] text-colorTextLightMode w-5 h-5</value>
      <webElementGuid>11ed35a6-4814-4d69-84d8-d84aba4ec806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>102f0387-565d-4900-a057-9a0753732d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;self-stretch h-fit flex-col justify-start items-start gap-1 p-2 flex&quot;]/a[@class=&quot;self-stretch inline-flex cursor-pointer px-2 rounded h-[34px] dark:bg-bgModifierHover bg-bgModifierHoverLight dark:hover:bg-bgModifierHover hover:bg-bgModifierHoverLight&quot;]/div[@class=&quot;grow w-5 flex-row items-center gap-2 flex&quot;]/div[@class=&quot;w-5 h-5 relative flex flex-row items-center&quot;]/div[@class=&quot;w-5 h-5 left-[1.67px] top-[1.67px] absolute&quot;]/svg[@class=&quot;dark:hover:text-white hover:text-black dark:text-[#B5BAC1] text-colorTextLightMode w-5 h-5&quot;]</value>
      <webElementGuid>3eb36d98-ccb5-463c-a6a8-00f33d152909</webElementGuid>
   </webElementProperties>
</WebElementEntity>
