<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_general</name>
   <tag></tag>
   <elementGuidId>ec2dcfa3-122c-4d10-a358-b4ee5c4d5f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div[2]/div/div[2]/div/a/span/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>80e3c65a-76c4-4877-9ee1-d43329592d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover font-medium dark:text-[#AEAEAE] text-colorTextLightMode</value>
      <webElementGuid>d9197825-8514-46e6-b87a-a2f726e53ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>general</value>
      <webElementGuid>eb8659a5-3881-4a4e-8de5-342ca866d9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;overflow-y-scroll flex-1 pt-3 space-y-[21px]  text-gray-300 scrollbar-hide pb-[120px]&quot;]/div[1]/div[@class=&quot;mt-[5px] space-y-0.5 text-[#AEAEAE]&quot;]/div[@class=&quot;relative group&quot;]/a[1]/span[@class=&quot;flex flex-row items-center px-2 mx-2 rounded relative p-1 dark:hover:bg-bgModifierHover hover:bg-bgLightModeButton&quot;]/p[@class=&quot;ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover font-medium dark:text-[#AEAEAE] text-colorTextLightMode&quot;]</value>
      <webElementGuid>71d60727-d19d-47a4-91b6-15d6b71b4e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div[2]/div/div[2]/div/a/span/p</value>
      <webElementGuid>55941d55-1feb-441c-9b3f-ff7d171efe35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/following::p[1]</value>
      <webElementGuid>4c7690f9-6c34-4445-9284-606c807f2864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[1]/following::p[1]</value>
      <webElementGuid>1b36324f-c8fa-4e07-a5e6-8393e3b39a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::p[7]</value>
      <webElementGuid>15b90935-cb44-4245-934b-8f3390843564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Threads'])[1]/preceding::p[10]</value>
      <webElementGuid>234c887f-444c-4fd0-b30b-5e954a44be91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='general']/parent::*</value>
      <webElementGuid>782e6cc0-544b-4cae-b70d-6e3eae968972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p</value>
      <webElementGuid>7139cf63-2d1b-4d81-bd50-0dd10512a42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'general' or . = 'general')]</value>
      <webElementGuid>13442cb8-167f-4a67-8b35-e9a91a1c9a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
