<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_member2</name>
   <tag></tag>
   <elementGuidId>d06def81-16e5-42d2-965b-03f63a837a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@class='text-base font-medium text-colorTextLightMode dark:text-white bg-transparent nameMemberProfile'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b94ee312-7084-4ad2-b7a8-a860b5b68529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-medium text-colorTextLightMode dark:text-white bg-transparent nameMemberProfile</value>
      <webElementGuid>146721e5-9998-4a64-a03f-64e8ea97da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>thuy.nguyenthithu1</value>
      <webElementGuid>0e377bd0-010d-48ea-b781-36bf9c0b44ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;memberList&quot;)/div[@class=&quot;self-stretch h-[268px] flex-col justify-start items-start flex p-4 gap-[24px] w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;relative group&quot;]/div[@class=&quot;relative gap-[5px] flex items-center cursor-pointer rounded&quot;]/div[@class=&quot;flex flex-col items-start&quot;]/p[@class=&quot;text-base font-medium text-colorTextLightMode dark:text-white bg-transparent nameMemberProfile&quot;]</value>
      <webElementGuid>231760a1-f0e1-47be-8de0-3b713c955a43</webElementGuid>
   </webElementProperties>
</WebElementEntity>
