<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What is channel, , s name)_Inp_00fae1</name>
   <tag></tag>
   <elementGuidId>6df1dab2-620a-4ed7-ab81-8cb7ec552d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>617070f6-81b0-40cd-bd29-2d0ff47033ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]</value>
      <webElementGuid>dc589720-5ed9-47df-9423-71b9967af11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the channel's name</value>
      <webElementGuid>79dfc8a2-c52e-4a21-b13e-609af0a1f04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;w-[100vw] h-[100vh] overflow-hidden fixed top-0 left-0 z-50 bg-black bg-opacity-80 flex flex-row justify-center items-center&quot;]/div[@class=&quot;z-60 w-full h-full sm:w-4/5 sm:max-h-[570px] md:w-[684px] bg-bgPrimary rounded-2xl flex-col justify-start  items-start gap-3 inline-flex&quot;]/div[@class=&quot;self-stretch md:h-96 flex-col justify-start items-start flex&quot;]/div[@class=&quot;self-stretch md:h-96 px-5 pt-8 flex-col justify-start items-start gap-3 flex&quot;]/div[@class=&quot;Frame408 self-stretch h-[84px] flex-col justify-start items-start gap-2 flex mt-1&quot;]/div[@class=&quot;ContentContainer self-stretch h-11 flex-col items-start flex&quot;]/div[@class=&quot;InputContainer self-stretch h-11 px-4 py-3 bg-neutral-950 rounded shadow border w-full border-blue-600  justify-start items-center gap-2 inline-flex&quot;]/div[@class=&quot;InputValue grow shrink basis-0 self-stretch justify-start items-center flex&quot;]/input[@class=&quot;Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]&quot;]</value>
      <webElementGuid>dc9a7766-55e1-4a83-aca9-efeca38a2513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>e45fc7f1-eb8d-4b36-8180-5fa65fb83474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>91c91277-d4c5-49fa-a7ad-6197f3823371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = concat(&quot;Enter the channel&quot; , &quot;'&quot; , &quot;s name&quot;)]</value>
      <webElementGuid>c3c24999-3c80-47b4-bb42-8ebd5bdf9be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
