<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What is category, , s name)_da_69c088</name>
   <tag></tag>
   <elementGuidId>e64ea693-7e7a-4a9c-8734-168b6fa921f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0f30768-f2ed-4a1e-bcee-0e4e84da86a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5a94356-8ba3-482d-bf69-df033c68e160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-bgTertiary bg-[#F0F0F0] font-[400]  px-[16px] rounded w-full dark:text-white text-black outline-none py-[8px] bg-black text-[14px] mt-2 mb-0 border-blue-600 border</value>
      <webElementGuid>041df6cd-15a7-40d8-b881-b92931419ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the category's name</value>
      <webElementGuid>33db216b-c516-4ed3-9cb3-20887abdcbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rk:&quot;)/div[@class=&quot;relative flex max-h-[90dvh] flex-col rounded-lg bg-white shadow dark:bg-gray-700&quot;]/div[@class=&quot;flex-1 overflow-auto p-6 bg-[#1E1E1E] px-6 py-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;dark:bg-bgTertiary bg-[#F0F0F0] font-[400]  px-[16px] rounded w-full dark:text-white text-black outline-none py-[8px] bg-black text-[14px] mt-2 mb-0 border-blue-600 border&quot;]</value>
      <webElementGuid>768c04c7-c8ed-4d79-86a1-9c4d32270d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>07d75744-f4ee-4be2-8416-c21bf483c349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rk:']/div/div[2]/div/div/input</value>
      <webElementGuid>dac07106-8797-4a36-9be2-7ebf93a278da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a5d485e9-4237-411d-8457-82627f1b7b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = concat(&quot;Enter the category&quot; , &quot;'&quot; , &quot;s name&quot;)]</value>
      <webElementGuid>64fa3985-ae34-4587-88c2-967d3f7406b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r3g:']/div/div[2]/div/div/input</value>
      <webElementGuid>6fdede0a-8fd9-4700-85c4-bf8af79b909b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
