<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Friends</name>
   <tag></tag>
   <elementGuidId>b02023c1-d256-444a-ad3b-d6334f6ca24a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[2]/div[4]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Friends&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5ff5872-fc0c-4257-82fb-40a9a2fafe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-3 rounded-[4px] w-full flex gap-4 items-center bg-bgTertiary</value>
      <webElementGuid>a3a26de0-1b63-40ab-a8d6-29655e13595c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Friends</value>
      <webElementGuid>f2417c96-972e-4273-906f-e6889148b25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative&quot;]/div[@class=&quot;flex-col w-[272px] bg-bgSurface relative&quot;]/div[@class=&quot;mt-5 px-2 py-1&quot;]/div[@class=&quot;w-full flex flex-row items-center&quot;]/button[@class=&quot;py-2 px-3 rounded-[4px] w-full flex gap-4 items-center bg-bgTertiary&quot;]</value>
      <webElementGuid>1010df4a-2c5b-47c6-99df-d7077bd72fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[4]/div/button</value>
      <webElementGuid>3a86e3dd-39b0-4031-8163-7da0ba5ef7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/preceding::button[2]</value>
      <webElementGuid>255eb6c9-7a3a-4dc0-8f1c-4e6e41d5c842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::button[2]</value>
      <webElementGuid>d0313f25-733e-4566-974c-f5a936cca8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Friends']/parent::*</value>
      <webElementGuid>9fd1f47e-c1f5-40f3-9b05-e8cb1a895cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0a9602df-419c-4519-bf67-0794a8696035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Friends' or . = 'Friends')]</value>
      <webElementGuid>0a4cef14-8405-43a8-b820-5bd366eabcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/preceding::button[2]</value>
      <webElementGuid>dace4671-adb2-4a90-9a63-d1f2177be13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::button[2]</value>
      <webElementGuid>cd1d36d9-879e-4f00-aead-91ace7b322d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
