<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3 Events1Browse ChannelsPUBLIC CHANNELSgeneral</name>
   <tag></tag>
   <elementGuidId>bdd6c904-9e86-4ed7-ac74-9a8d649a30fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#channelList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;3 Events 1 Browse Channels PUBLIC CHANNELS general Add Person&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09f3c304-1512-45cb-a347-7a568fe283f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overflow-y-scroll scrollbar-thin overflow-x-hidden w-[100%] h-[100%] pb-[10px] </value>
      <webElementGuid>e730c00c-0e1b-4081-ac0b-b56404b59411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>channelList</value>
      <webElementGuid>423b0d49-c5f4-4d8f-bba7-f806a04ea03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb900fe7-f868-4efa-bd61-cd3540ad5324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 Events1Browse ChannelsPUBLIC CHANNELSgeneral</value>
      <webElementGuid>56c93c8d-1ef7-4328-8821-b8321fde5cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)</value>
      <webElementGuid>3996f6e5-f8f4-49d2-a3c2-55acec314ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='channelList']</value>
      <webElementGuid>c32c2de1-ed3c-44ba-b9a5-3316991e275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div/div[3]</value>
      <webElementGuid>2d220292-6268-4666-a186-b666a74df86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::div[9]</value>
      <webElementGuid>9d3901ea-8ff7-4c30-9093-0db8221636bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>edce21a6-905c-40b9-934d-585f0ad3dab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'channelList' and (text() = '3 Events1Browse ChannelsPUBLIC CHANNELSgeneral' or . = '3 Events1Browse ChannelsPUBLIC CHANNELSgeneral')]</value>
      <webElementGuid>cbe1dfb4-ecde-4de5-b6fb-12152353ac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
