<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CCreate a Clan</name>
   <tag></tag>
   <elementGuidId>44c44440-7e68-47a9-999b-70c7e50789c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div[2]/div[2]/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb1ed145-40eb-4286-b846-4e345c8c71ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-4 w-10/12</value>
      <webElementGuid>3ffe8a5b-ef10-45e2-9c56-6ea14ee91b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CCreate a Clan</value>
      <webElementGuid>12da60a1-968f-4197-96fa-4c7ab739a37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;relative py-2&quot;]/div[@class=&quot;absolute bottom-0 right-0 top-0 left-[60px] z-10 bg-bgSecondary&quot;]/div[@class=&quot;flex w-64 flex-col text-[16px] px-3 py-2 gap-2 z-50 border-[1px] border-bg-bgSecondary dark:border-borderDefault border-[#E1E1E1] dark:bg-bgProfileBody bg-[#F0F0F0] duration-100 rounded&quot;]/div[@class=&quot;overflow-y-auto max-h-36 hide-scrollbar&quot;]/button[@class=&quot;w-full  flex py-1 px-2 items-center cursor-pointer justify-between rounded-md dark:bg-[#151C2B] bg-bgLightModeButton duration-100 dark:text-contentPrimary text-black font-bold&quot;]/div[@class=&quot;flex items-center gap-4 w-10/12&quot;]</value>
      <webElementGuid>a9220e75-cc0c-429c-a850-24e28356d16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/button/div</value>
      <webElementGuid>3157fade-0d3c-4a90-97cd-3998856f448b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::div[6]</value>
      <webElementGuid>374144f0-aed8-4a1c-9e2a-fb79f1cf7aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>7fa7bda9-c318-4fa5-8965-71f47b8df75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CCreate a Clan' or . = 'CCreate a Clan')]</value>
      <webElementGuid>bd87ebcb-4553-43cc-a66e-6de1509fb5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
