<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOMU</name>
   <tag></tag>
   <elementGuidId>261fe896-264c-4250-aab8-ad22bc1b746a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div[2]/div[2]/div/div/button[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35a5ebd4-6872-49c5-a468-302d7116ae91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-4 w-10/12</value>
      <webElementGuid>77bb761e-f390-4dd8-a981-2503043ae044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOMU</value>
      <webElementGuid>d02dd689-9d7c-4b21-b38d-96841b198523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;relative py-2&quot;]/div[@class=&quot;absolute bottom-0 right-0 top-0 left-[60px] z-10 bg-bgSecondary&quot;]/div[@class=&quot;flex w-64 flex-col text-[16px] px-3 py-2 gap-2 z-50 border-[1px] border-bg-bgSecondary border-borderDefault bg-bgProfileBody rounded&quot;]/div[@class=&quot;overflow-y-auto max-h-36&quot;]/button[@class=&quot;w-full  flex py-1 px-2 items-center cursor-pointer justify-between rounded-md text-contentSecondary&quot;]/div[@class=&quot;flex items-center gap-4 w-10/12&quot;]</value>
      <webElementGuid>a5459739-d44c-460c-91b4-f6590ef31d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/button[3]/div</value>
      <webElementGuid>f6e0dbc8-b824-4402-aeb4-0d4ad61cdae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Clan 1234'])[1]/following::div[1]</value>
      <webElementGuid>36f0e49d-8651-47d4-9a84-c98b0291c387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clan_komu'])[1]/following::div[2]</value>
      <webElementGuid>1b5c3df9-377c-4968-85b1-09a8128446ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('test', &quot;'&quot;, 's clan@!#$%^&amp;*()_+-')])[1]/preceding::div[1]</value>
      <webElementGuid>49380e8a-1da2-41f1-a551-edb55c04365d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div</value>
      <webElementGuid>19625b7d-15fe-4826-b687-948e84d80e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KOMU' or . = 'KOMU')]</value>
      <webElementGuid>bc7add41-2b3c-4f41-855f-adcb1e11d68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
