<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WELCOME BACKSo glad to meet you againCo_e1c4c1</name>
   <tag></tag>
   <elementGuidId>2e041f06-fd94-4642-a72c-dd665d409511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-screen.h-screen.overflow-x-hidden.overflow-y-scroll.scrollbar-hide.flex.items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-layout']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#app-layout div >> internal:has-text=&quot;WELCOME BACKSo glad to meet you again!Continue with GoogleorEmail or Phone numbe&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f800d3a-6b73-4cea-b754-b8f9a6b8108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> w-screen h-screen  overflow-x-hidden overflow-y-scroll  scrollbar-hide flex items-center</value>
      <webElementGuid>fa779777-e2bc-4c9f-913e-40e5c4be3da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WELCOME BACKSo glad to meet you again!Continue with GoogleorEmail or Phone number✱Password✱Forgot your password?Sign inNeed an account?Sign uperrorPasswordSign in by QR codeUse Mezon on mobile to scan QR</value>
      <webElementGuid>93bc7269-1514-4646-b479-8dda33075496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-layout&quot;)/div[1]/div[@class=&quot;w-screen h-screen  overflow-x-hidden overflow-y-scroll  scrollbar-hide flex items-center&quot;]</value>
      <webElementGuid>c9cce19d-bc97-4d7d-a536-7f448270fa77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-layout']/div/div</value>
      <webElementGuid>33c30818-33f9-4200-8efa-a589cae43db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>9e4a64ca-560f-45b7-84fb-9dd56e2de8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WELCOME BACKSo glad to meet you again!Continue with GoogleorEmail or Phone number✱Password✱Forgot your password?Sign inNeed an account?Sign uperrorPasswordSign in by QR codeUse Mezon on mobile to scan QR' or . = 'WELCOME BACKSo glad to meet you again!Continue with GoogleorEmail or Phone number✱Password✱Forgot your password?Sign inNeed an account?Sign uperrorPasswordSign in by QR codeUse Mezon on mobile to scan QR')]</value>
      <webElementGuid>8ea47d0e-f69c-4c70-9ee0-9e6119b72261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
