<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome to  generalThis is the start of_02ab9c</name>
   <tag></tag>
   <elementGuidId>a91d9c6b-e069-40aa-8203-cd0716467efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollLoading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollLoading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scrollLoading</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>027a4665-dc91-4b18-89e4-9d3a5d625cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#26262B] relative</value>
      <webElementGuid>425814d2-6a26-4078-9117-9eaea47f14db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrollLoading</value>
      <webElementGuid>d8e74892-50a0-4a4f-8797-785bbc75a1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to # generalThis is the start of the #general channel.</value>
      <webElementGuid>0bc1bba9-6a65-41d4-bbd7-91a1d040fbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollLoading&quot;)</value>
      <webElementGuid>a90626d0-68b0-44ae-a48d-b102662d1338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='scrollLoading']</value>
      <webElementGuid>5e5a4a92-c4a4-4798-853f-214059c619ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div/div</value>
      <webElementGuid>0f3d447d-91f4-4786-9f64-a44b07783e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Threads'])[1]/following::div[13]</value>
      <webElementGuid>a5c52f93-98b0-44cd-8aa9-5b752aaac3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::div[27]</value>
      <webElementGuid>faca395c-f40f-4a00-922a-fdd777d3ccf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>ee19373b-1040-47df-9b38-6e36e29b3b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'scrollLoading' and (text() = 'Welcome to # generalThis is the start of the #general channel.' or . = 'Welcome to # generalThis is the start of the #general channel.')]</value>
      <webElementGuid>dabf5e64-5804-4fee-9c19-f753a63c7f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
