<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Friends_clan</name>
   <tag></tag>
   <elementGuidId>b2330d0f-d748-4373-8fdf-b328770f5b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.clan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/a/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;logoMezon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1f79154-2c75-431e-a2b9-9a53b9193375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon-logo-mezon.svg</value>
      <webElementGuid>dd1116b2-5917-4937-9595-3577e2a2fd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logoMezon</value>
      <webElementGuid>c36d229c-9dbb-4a3b-831a-f40fc3857611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>e6f1c815-dcf8-4f1f-aa3d-3235c286ece0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>cacbf967-997a-44a3-a737-f1691839c818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clan</value>
      <webElementGuid>38103905-a83c-48af-8079-bddb4cc7ac05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/a[@class=&quot;active&quot;]/div[@class=&quot;group block relative rounded-3xl&quot;]/div[@class=&quot;group-active:translate-y-px&quot;]/div[@class=&quot;rounded-xl bg-brand text-white bg-bgTertiary flex items-center justify-center w-12 h-12 transition-all duration-200 overflow-hidden&quot;]/div[1]/img[@class=&quot;clan&quot;]</value>
      <webElementGuid>f5fbbb2a-a5ff-4f4b-95ed-c027abbd4c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/a/div/div[2]/div/div/img</value>
      <webElementGuid>6ae0d940-8983-46ac-9b5c-48be922e45b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logoMezon']</value>
      <webElementGuid>cf3713aa-c6c9-4639-a8a0-92abc3f0137d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ee637ed2-914e-4df0-8ffe-5bf5cc5526a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon-logo-mezon.svg' and @alt = 'logoMezon']</value>
      <webElementGuid>bbacf912-76b1-42ba-8911-efa7166397ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
