<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Emoji_w-full h-auto</name>
   <tag></tag>
   <elementGuidId>44507729-3aef-45d3-b4d7-aed0d0310627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-full.h-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4116f3af-3b84-428d-a172-daa17ff40043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif</value>
      <webElementGuid>739eed5c-16b9-4cf4-b017-01d14e36d04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif</value>
      <webElementGuid>0395f49e-4344-45cd-930d-aef11f33763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto</value>
      <webElementGuid>4e5a52e0-ce92-44f8-9ad8-41512861fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;right-[2px] absolute z-10 animate-scale_up origin-bottom-right&quot;]/div[@class=&quot;w-[370px] max-sm:w-full max-sm:pt-0 max-sm:rounded-none max-sm:mt-[-0.5rem]
			sbm:w-[500px] max-sbm:w-[312px] max-sbm:rounded-lg h-fit rounded-lg dark:bg-bgSecondary bg-bgLightMode shadow shadow-neutral-900 z-30
			 min-h-[500px]&quot;]/div[@class=&quot;w-full min-h-[400px] text-center md:w-[500px]&quot;]/div[@class=&quot;flex h-full pr-1 w-full md:w-[500px]&quot;]/div[@class=&quot;outline-none&quot;]/div[@class=&quot;mx-2 flex justify-center h-[400px] overflow-y-scroll hide-scrollbar flex-wrap&quot;]/div[@class=&quot;grid grid-cols-3  gap-1&quot;]/div[@class=&quot;order-0 overflow-hidden cursor-pointer&quot;]/img[@class=&quot;w-full h-auto&quot;]</value>
      <webElementGuid>af1c7ee9-33b6-47b4-868f-ec078743d7e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>3355a8a2-6545-4739-a6fa-42dc1e9795af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif']</value>
      <webElementGuid>93cfec04-3c85-4728-8bb7-4f9b8093aba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/img</value>
      <webElementGuid>b1cf11dc-aa1e-4902-8a25-09af3c54f9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif' and @alt = 'https://media.tenor.com/m-NzM9Ws0MwAAAAC/awesome-grandma.gif']</value>
      <webElementGuid>62c2684f-9aa5-43ff-91c3-a18a72aa6c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
