<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-main-clan-name</name>
   <tag></tag>
   <elementGuidId>c20cf2b4-77c7-4933-9f10-db77afc07dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-white.text-lg.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[2]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;E2E-CLAN&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fc9de938-cac5-490b-ba78-cb7af05c7133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white text-lg font-bold</value>
      <webElementGuid>34046b7d-9c81-4303-8b11-7928b6cf8a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E2E-CLAN</value>
      <webElementGuid>1b39cadf-faf2-464f-82e9-4d8cc54a305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative&quot;]/div[@class=&quot;flex flex-row flex-1 bg-bgSurface&quot;]/div[@class=&quot;flex-col max-w-[272px] bg-bgSurface relative overflow-hidden&quot;]/div[@class=&quot;h-[60px] relative bg-gray-950&quot;]/div[@class=&quot;border-b border-borderDefault cursor-pointer w-[272px] p-3 left-0 top-0 absolute flex h-heightHeader justify-between items-center gap-2 bg-[#030712]&quot;]/p[@class=&quot;text-white text-lg font-bold&quot;]</value>
      <webElementGuid>b641b6b8-f3e3-4e45-a67e-fded6c8ff529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div/div/div/p</value>
      <webElementGuid>3db71b36-22e4-4044-9011-20257f9ad5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::p[2]</value>
      <webElementGuid>6184ed01-fb6b-4000-ba2c-2480444a168b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Channels'])[1]/preceding::p[1]</value>
      <webElementGuid>7cab7dd9-9c63-4287-8a24-ff4d65f65683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/preceding::p[1]</value>
      <webElementGuid>81b0e037-cdcc-43c6-87e4-4b9318919b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E2E-CLAN']/parent::*</value>
      <webElementGuid>4cd3b543-0dae-4387-9e8f-c438d018ff50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>7df5e087-2ae2-4ab6-bfc2-4a7e9d68bf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'E2E-CLAN' or . = 'E2E-CLAN')]</value>
      <webElementGuid>52c122d9-2076-4302-a996-8db86fe0e8bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
