<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_general</name>
   <tag></tag>
   <elementGuidId>c3408fc0-f53a-4d83-b788-e9b5f22671ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div[2]/div/div[2]/div/a/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;general&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>530f4cb7-438e-4334-9d2d-20af12735ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 font-medium text-[#AEAEAE] w-full group-hover:text-white text-[15px] focus:bg-[#36373D] font-medium text-white</value>
      <webElementGuid>3cfbd7f5-02d5-4f76-8b1a-944fc2b1b3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>general</value>
      <webElementGuid>a9eb14f9-3aed-4cb5-a6a5-cb9060985755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;overflow-y-scroll flex-1 pt-3 space-y-[21px]  text-gray-300 scrollbar-hide pb-[120px]&quot;]/div[1]/div[@class=&quot;mt-[5px] space-y-0.5 text-[#AEAEAE]&quot;]/div[@class=&quot;relative group&quot;]/a[1]/span[@class=&quot;flex flex-row items-center px-2 mx-2 rounded relative p-1 bg-[#36373D]&quot;]/p[@class=&quot;ml-2 font-medium text-[#AEAEAE] w-full group-hover:text-white text-[15px] focus:bg-[#36373D] font-medium text-white&quot;]</value>
      <webElementGuid>07608de2-6ba3-4a60-aa35-1f75742cfcd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div[2]/div/div[2]/div/a/span/p</value>
      <webElementGuid>ee63e798-26db-4350-9dbf-b154107c5ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/following::p[1]</value>
      <webElementGuid>d2e14099-2c8d-45e4-a91e-c689c53eb170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Channels'])[1]/following::p[1]</value>
      <webElementGuid>0a48453f-bded-4330-8c9d-980e0ff087e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark As Read'])[1]/preceding::p[1]</value>
      <webElementGuid>73c9e70f-7224-479a-a652-be0847e32df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite People'])[1]/preceding::p[1]</value>
      <webElementGuid>922f25e3-2b65-4584-8d78-d21565e3aada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='general']/parent::*</value>
      <webElementGuid>89729084-133b-4327-8d00-2aae33f78ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p</value>
      <webElementGuid>55654151-1198-4cd1-8514-f93e0635e812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'general' or . = 'general')]</value>
      <webElementGuid>853e1985-8dc2-44f0-8cfc-d5019173b407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
