<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hanoi1</name>
   <tag></tag>
   <elementGuidId>e51365a8-c3b2-46c7-b1ef-41adfa1acca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1822908138555183104']/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hanoi1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e9de7ff4-d634-4beb-ade6-cb759c9a84b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover font-medium dark:text-channelTextLabel text-colorTextLightMode</value>
      <webElementGuid>15d69d1f-97e8-4275-97f0-1a2ff4902fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hanoi1</value>
      <webElementGuid>2c6e82f5-7a6a-4921-8e1b-b6c6992acccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1822908138555183104&quot;)/span[@class=&quot;flex flex-row items-center px-2 mx-2 rounded relative p-1 dark:hover:bg-bgModifierHover hover:bg-bgLightModeButton cursor-pointer&quot;]/p[@class=&quot;ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover font-medium dark:text-channelTextLabel text-colorTextLightMode&quot;]</value>
      <webElementGuid>7b136ade-5f01-4043-bfe9-f8e7aa7532c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1822908138555183104']/span/p</value>
      <webElementGuid>76c34f05-1849-4d57-b77d-dcf5398cf1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/following::p[1]</value>
      <webElementGuid>9d6bf98f-cd83-47a3-a9eb-62a573634d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorite channel'])[1]/following::p[1]</value>
      <webElementGuid>acac5350-b06e-4c36-a16a-2e077fd13f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hello world!!!'])[1]/preceding::p[1]</value>
      <webElementGuid>6c0fe6fe-54c7-4011-8831-ac7c2fcf091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='geBXclVQui'])[2]/preceding::p[2]</value>
      <webElementGuid>348a37f9-673e-4f66-9394-549d5e2c8f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hanoi1']/parent::*</value>
      <webElementGuid>2d7b9714-8c10-4926-9fef-af7727c906c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p</value>
      <webElementGuid>df6be30b-0490-4bf3-817e-c2dfc73568be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hanoi1' or . = 'Hanoi1')]</value>
      <webElementGuid>dac564fa-7b4f-4fe0-9e83-c4b375a3da0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
