<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Password</name>
   <tag></tag>
   <elementGuidId>8b5dcc6e-05a1-45d2-99f2-c2ea9d73720f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-layout']/div/div/div/div/div/div[3]/div[2]/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Password&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7e242751-8a91-4412-9688-dd076d2f781c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit h-fit text-left text-sm font-medium text-[#cccccc] leading-[150%]</value>
      <webElementGuid>b821d53e-4abe-483b-8f44-7d7b25497bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>03d08973-f312-4856-8916-3fbb24f1bf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-layout&quot;)/div[1]/div[@class=&quot;w-screen h-screen  overflow-x-hidden overflow-y-scroll  scrollbar-hide flex items-center&quot;]/div[@class=&quot;justify-center items-center flex w-full h-full sm:max-h-[580px] sm:h-9/10 sm:max-w-[450px] lg:min-w-[850px] lg:max-h-[620px]  rounded-none sm:rounded-2xl lg:p-12 px-0 bg-[#0b0b0b] flex-col mx-auto&quot;]/div[@class=&quot;relative top-0 flex-col pb-0 lg:top-0 lg:pb-0 flex lg:flex-row lg:gap-x-12 items-center w-full overflow-y-auto hide-scrollbar lg:overflow-y-visible&quot;]/div[@class=&quot;flex-col justify-start items-center flex h-fit p-0 gap-2 pb-2 lg:pb-0 md:gap-4 w-9/10&quot;]/div[@class=&quot;flex-col justify-start items-center flex lg:w-[496px] h-fit lg:px-0 w-450 max-w-full&quot;]/div[@class=&quot;flex-col justify-start items-start flex w-full h-fit gap-y-5&quot;]/div[@class=&quot;flex-col justify-start items-start flex w-full h-fit gap-y-5&quot;]/div[@class=&quot;flex-col justify-start items-start flex w-full h-fit gap-y-3&quot;]/div[@class=&quot;flex-row justify-start items-center flex w-full h-fit gap-x-1&quot;]/p[@class=&quot;w-fit h-fit text-left text-sm font-medium text-[#cccccc] leading-[150%]&quot;]</value>
      <webElementGuid>0e3c8d4a-b331-4bc4-ba71-dd1cd95638f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-layout']/div/div/div/div/div/div[3]/div[2]/div/div[2]/div/p</value>
      <webElementGuid>c8770dfc-51a4-443e-97e7-53c0cfc298b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WELCOME BACK'])[1]/following::p[6]</value>
      <webElementGuid>d3fd8ff2-4098-42b0-9d92-6217deecf2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password?'])[1]/preceding::p[2]</value>
      <webElementGuid>ac3bbfc2-d6d0-4f9b-aa90-582885d0143c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::p[3]</value>
      <webElementGuid>a5453910-a192-480b-bcf4-d58ab383d0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password']/parent::*</value>
      <webElementGuid>57737387-89da-428d-ac13-b0a0d2026d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/p</value>
      <webElementGuid>d8aba974-aa6a-4f22-9514-eae2b5044154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>2500fecd-5f98-46c7-8a3f-ef64d78a7895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
