<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CLAN01-1714640930815</name>
   <tag></tag>
   <elementGuidId>edd3dee2-7b27-45a5-a6a2-00f81ce32bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div[2]/div[2]/div/div/div[14]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CLAN01-1714640930815&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e30c876-d7f1-4047-82f4-99e2320f4438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[16px] one-line</value>
      <webElementGuid>f1bb9060-659e-4fb9-a696-3cf3a896c458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLAN01-1714640930815</value>
      <webElementGuid>b8469528-9263-436e-8395-37b288eeee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;relative py-2&quot;]/div[@class=&quot;absolute bottom-0 right-0 top-0 left-[60px] z-10 bg-bgSecondary&quot;]/div[@class=&quot;flex w-64 flex-col text-[16px] px-3 py-2 gap-2 z-50 border-[1px] border-bg-bgSecondary border-borderDefault bg-bgSecondary rounded-lg&quot;]/div[@class=&quot;overflow-y-auto max-h-36&quot;]/div[@class=&quot;w-auto flex py-1 px-2 items-center cursor-pointer justify-between rounded-md text-contentSecondary&quot;]/div[@class=&quot;flex items-center gap-4 w-10/12&quot;]/span[@class=&quot;text-[16px] one-line&quot;]</value>
      <webElementGuid>52b234b2-8267-481d-b1ec-a3141b198816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/div[14]/div/span</value>
      <webElementGuid>dd4af2ff-369f-4666-ac18-7e598ca4f951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[11]/following::span[1]</value>
      <webElementGuid>705c8253-d66b-4cd8-9889-8928b473b3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAN01-1714640860665'])[1]/following::span[1]</value>
      <webElementGuid>3958c6d6-3908-4495-9c6a-f1b2096dab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Clan'])[1]/preceding::span[1]</value>
      <webElementGuid>d4e2fc12-98b6-4169-a866-b653ad8b046e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friends'])[1]/preceding::span[2]</value>
      <webElementGuid>47aba9a4-7370-4214-b904-bc961c7d4020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLAN01-1714640930815']/parent::*</value>
      <webElementGuid>e764c6a4-6fa1-4dc6-84b7-201ba90c5e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/span</value>
      <webElementGuid>31971afe-80cc-4f29-b2ee-c9e2f7d0d168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CLAN01-1714640930815' or . = 'CLAN01-1714640930815')]</value>
      <webElementGuid>cc2b54e4-8d85-48c7-a3d7-f45adbfa90bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
