<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Clan</name>
   <tag></tag>
   <elementGuidId>8127db44-5934-4789-8cba-7ad3155c6e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div[2]/div[2]/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91616711-207a-46af-a8c0-8b98bc5544de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[16px]</value>
      <webElementGuid>8b9fc8cc-9f79-45e8-8f82-a29148a80230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Clan</value>
      <webElementGuid>5035ee6c-4ee2-4de3-a5b4-452b4f038768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;relative py-2&quot;]/div[@class=&quot;absolute bottom-0 right-0 top-0 left-[60px] z-10 bg-bgSecondary&quot;]/div[@class=&quot;flex w-64 flex-col text-[16px] px-3 py-2 gap-2 z-50 border-[1px] border-bg-bgSecondary border-borderDefault bg-bgProfileBody rounded&quot;]/div[@class=&quot;w-auto flex py-1 px-2 items-center justify-between text-contentSecondary rounded-md cursor-pointer hover:bg-[#155EEF1A]&quot;]/button[@class=&quot;flex items-center gap-4 w-10/12&quot;]/span[@class=&quot;text-[16px]&quot;]</value>
      <webElementGuid>d42c1ec2-9038-4112-bc9a-dad12d1e53ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div[2]/button/span</value>
      <webElementGuid>b10668c2-620b-44eb-851b-5bab546b5e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test-create-a_Clan'])[1]/following::span[1]</value>
      <webElementGuid>d228fcd3-d5f5-4d34-891c-1b78fdc88965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friends'])[1]/preceding::span[1]</value>
      <webElementGuid>a44738f4-40af-4987-9668-8a644b02cf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/preceding::span[1]</value>
      <webElementGuid>7b5c05ff-2e87-4260-965e-539f6d30412a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Clan']/parent::*</value>
      <webElementGuid>5b7352ba-3391-44fd-a89f-14cdac014b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>cca5b413-f9e5-495c-a07a-e367f871a36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add Clan' or . = 'Add Clan')]</value>
      <webElementGuid>a2dec3e2-a25d-40b3-bdd0-2db9dfb17e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Clan 123'])[1]/following::span[1]</value>
      <webElementGuid>23017b7b-ebbc-4bc0-904f-b2e86d3f9513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Clan'])[2]/following::span[2]</value>
      <webElementGuid>a18d5d14-4e7a-495d-89dd-33e77aa5bb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/preceding::span[1]</value>
      <webElementGuid>d5c061ab-4ddb-4b1e-812c-6ff31f26674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='thread1'])[1]/preceding::span[3]</value>
      <webElementGuid>b03e7f34-693b-462b-b550-1e9788a95f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
