<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KOMU</name>
   <tag></tag>
   <elementGuidId>b5db9176-8918-44a4-b5d3-3be6fff885c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div[2]/div[2]/div/div/button[4]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;https://cdn.mezon.vn/New Project (1).png KOMU&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00bc50ae-397b-423e-8223-b896be36f6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[16px] one-line</value>
      <webElementGuid>8d9f0516-1c36-44cd-8d0a-1531cccc8a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOMU</value>
      <webElementGuid>11515181-2d54-4212-9005-2b43017884f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;relative py-2&quot;]/div[@class=&quot;absolute bottom-0 right-0 top-0 left-[60px] z-10 bg-bgSecondary&quot;]/div[@class=&quot;flex w-64 flex-col text-[16px] px-3 py-2 gap-2 z-50 border-[1px] border-bg-bgSecondary border-borderDefault bg-bgProfileBody rounded&quot;]/div[@class=&quot;overflow-y-auto max-h-36&quot;]/button[@class=&quot;w-full  flex py-1 px-2 items-center cursor-pointer justify-between rounded-md text-contentSecondary&quot;]/div[@class=&quot;flex items-center gap-4 w-10/12&quot;]/span[@class=&quot;text-[16px] one-line&quot;]</value>
      <webElementGuid>140255b6-80ae-48a8-93c5-750a4247e164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/button[4]/div/span</value>
      <webElementGuid>baf80bad-d92e-4109-8a34-c6e2f7fc6024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clan_komu'])[1]/following::span[1]</value>
      <webElementGuid>b4fce6e5-0205-4e95-a399-c6d0710fdeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Clan 1234'])[1]/following::span[2]</value>
      <webElementGuid>23445f70-f27d-46dc-a369-180d3eda40ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('test', &quot;'&quot;, 's clan@!#$%^&amp;*()_+-')])[1]/preceding::span[1]</value>
      <webElementGuid>7a8289f3-1cd7-4ea6-a2ed-53c5da3ca9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/preceding::span[2]</value>
      <webElementGuid>0c86ecbc-6857-4c2e-bf53-f3edf0fdc516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOMU']/parent::*</value>
      <webElementGuid>742b769c-777d-49de-b566-597bf2291ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/div/span</value>
      <webElementGuid>9e9ea73f-0983-4baf-bb12-2137770a6871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KOMU' or . = 'KOMU')]</value>
      <webElementGuid>e856f5e4-1c97-45f3-87a7-a920d9631f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/button[2]/div/span</value>
      <webElementGuid>ac9e4c8d-ce40-4996-acf9-6858d7bfb17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Clan 1234'])[1]/following::span[1]</value>
      <webElementGuid>06c3f485-3c74-446e-8759-3e56dd57b3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div/span</value>
      <webElementGuid>7e0aa27d-8d8b-47d0-a0c3-418d69b0ecd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div[2]/div[2]/div/div/button/div/span</value>
      <webElementGuid>5fbdbf38-5df5-4857-b076-2bf445139892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>fcb3036a-8727-4186-9d55-babd459dfc7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
