<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Hi Nguyen Phu</name>
   <tag></tag>
   <elementGuidId>69f90072-8184-4fca-badf-7e18a0bb3cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editorReactMention']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editorReactMention</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Write your thoughts here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d69f188-840a-4315-a8cb-2b6eb1fd1fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>6878c9be-9f83-4b5b-99dd-4b710317928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughts here...</value>
      <webElementGuid>b05e55c9-54f0-4111-b3f7-399e427b0252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>a11dce6f-5462-4909-855d-897b4246b300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi Nguyen Phu</value>
      <webElementGuid>b1d91f26-b208-4781-a3e6-daa4a082f251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorReactMention&quot;)</value>
      <webElementGuid>9c05e051-f75e-454d-9543-b8b7c905c917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editorReactMention']</value>
      <webElementGuid>6dc108f3-c2bd-4880-a9f3-743eb3628364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div[2]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>7149077c-4f0e-45e2-844c-3800a90f2952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi Nguyen Phu'])[1]/following::textarea[1]</value>
      <webElementGuid>4bd5222a-32db-4c0a-a2c1-ea9c6c8a89de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[2]/following::textarea[1]</value>
      <webElementGuid>7b23b2ee-7eb8-4a8c-a4e0-355a4092e7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cb93c305-81f5-4f80-baba-cbd3a0f23139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughts here...' and (text() = 'Hi Nguyen Phu' or . = 'Hi Nguyen Phu')]</value>
      <webElementGuid>1e89c574-76f9-4e52-8168-be7c0a6342a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
