<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Hi</name>
   <tag></tag>
   <elementGuidId>06059205-ee13-4e32-9cd2-24fcbc9ea1e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editorReactMention']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editorReactMention</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Write your thoughts here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>98ff3e24-9ab2-43b6-9e0b-25b82bc4d3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>4933d09a-55cd-4b1d-ac82-2f34b14d6fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughts here...</value>
      <webElementGuid>c1213015-0af3-453b-ad1e-261d54d8d05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>3ffd04df-7225-4895-9540-b852d302b64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi</value>
      <webElementGuid>d40c7ba0-d15b-4aa6-9529-4ba7b711e5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorReactMention&quot;)</value>
      <webElementGuid>263a7f47-dfae-44c1-b164-cf6834eab94f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editorReactMention']</value>
      <webElementGuid>52f66996-8684-4992-8c6f-746b0e8884b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div[2]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>c5d60766-e2e0-405a-976c-36ceee3536ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi'])[1]/following::textarea[1]</value>
      <webElementGuid>ccb2da29-adca-4d04-8380-e091ca060928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[2]/following::textarea[1]</value>
      <webElementGuid>52fb1c72-4d01-48d2-a06a-148b9d6f6320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>22d52b68-74dc-439c-90db-2f5e9b95f504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughts here...' and (text() = 'Hi' or . = 'Hi')]</value>
      <webElementGuid>f13de2a3-21d3-4dc8-8b09-4a0edc089d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
