<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_general</name>
   <tag></tag>
   <elementGuidId>07adf897-0826-4a64-92cb-a8aeac080f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1810967355170230272']/a/span/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;general&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>41e6e2a8-5534-495c-b138-eb2805caf308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover dark:text-white text-black dark:font-medium font-semibold</value>
      <webElementGuid>85a56175-3315-4fe7-b1e7-828f62f64819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>general</value>
      <webElementGuid>293ad55b-b4e7-40dd-97c4-dcc52349926a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1810967355170230272&quot;)/a[@class=&quot;channel-link&quot;]/span[@class=&quot;flex flex-row items-center px-2 mx-2 rounded relative p-1 dark:bg-bgModifierHover bg-bgLightModeButton&quot;]/p[@class=&quot;ml-2 w-full dark:group-hover:text-white group-hover:text-black text-base focus:bg-bgModifierHover dark:text-white text-black dark:font-medium font-semibold&quot;]</value>
      <webElementGuid>1acb05a7-e687-42ee-9cca-6e9934451cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1810967355170230272']/a/span/p</value>
      <webElementGuid>9921c193-7b7d-45ad-9f15-40b1cfa02350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[1]/following::p[1]</value>
      <webElementGuid>d382332d-92c7-4e83-8e96-720be11f0ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorite channel'])[1]/following::p[1]</value>
      <webElementGuid>36af109e-0101-4846-a966-06108fe8a423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hello world!!!'])[1]/preceding::p[3]</value>
      <webElementGuid>c084afe7-ea43-4f86-a0cc-1371e5715b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='geBXclVQui'])[2]/preceding::p[4]</value>
      <webElementGuid>02f5e988-1d99-485a-a006-31b407209d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='general']/parent::*</value>
      <webElementGuid>3734d5cb-5662-44ac-8ac4-7baf5b31f5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p</value>
      <webElementGuid>6dc8f43f-25cb-42bc-a9ff-ab1c2c674d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'general' or . = 'general')]</value>
      <webElementGuid>e7242f39-a7fc-4b4a-9103-1b012bcc9b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
