<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notification Settings_w-fit</name>
   <tag></tag>
   <elementGuidId>ab5d79b3-74a5-464a-a9e7-eb4573fff50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[3]/div/div/div[2]/div/div/div/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.relative > div:nth-child(4) > .w-fit</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0cad54e-fdc9-4ccb-9849-23cdbdcc7c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit</value>
      <webElementGuid>d3633705-3e16-49c3-87db-7a87a9dfced9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>flowbite-tooltip-target</value>
      <webElementGuid>cd3688f1-aa5f-4b7c-b56e-7c4b7ab888de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r10:</value>
      <webElementGuid>0c64a4b8-5c20-4069-bc06-3f362374d33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen min-[480px]:pl-[72px]  overflow-hidden text-gray-100 relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-1 shrink min-w-0 gap-2&quot;]/div[@class=&quot;flex flex-col flex-1 shrink  min-w-0 bg-transparent h-[100%] overflow-visible&quot;]/div[@class=&quot;max-sbm:z-20 flex h-heightTopBar p-3 min-w-0 items-center flex-shrink dark:bg-bgPrimary bg-bgLightPrimary shadow-inner border-b-[1px] dark:border-bgTertiary border-bgLightTertiary false left-0&quot;]/div[@class=&quot;items-center h-full ml-auto flex&quot;]/div[@class=&quot;justify-end items-center gap-2 flex&quot;]/div[@class=&quot;hidden sbm:flex&quot;]/div[@class=&quot;relative justify-start items-center gap-[15px] flex mr-4&quot;]/div[@class=&quot;relative leading-5 h-5&quot;]/div[@class=&quot;w-fit&quot;]</value>
      <webElementGuid>e947e560-dfce-4fca-a396-2f9b89290a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[3]/div/div/div[2]/div/div/div/div[4]/div</value>
      <webElementGuid>60a9e227-2122-46c9-990e-b2b859659cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Settings'])[1]/following::div[3]</value>
      <webElementGuid>ad575b4e-bcbb-4f59-8975-4dd227bcd7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Threads'])[1]/following::div[8]</value>
      <webElementGuid>51e51a0b-0c54-4f27-a6ae-4dddec4a0c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned Messages'])[1]/preceding::div[1]</value>
      <webElementGuid>472fad60-2f26-4804-a8a5-c124a57e7625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned Messages'])[2]/preceding::div[4]</value>
      <webElementGuid>07c64e9a-cc70-4cad-afdc-266055623536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div[4]/div</value>
      <webElementGuid>fb74a02a-5cbe-4a09-91fe-066cea3df8f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
