<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DM_member_1</name>
   <tag></tag>
   <elementGuidId>fc53c287-b68e-4547-8e4a-33dd37512d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[2]/div[5]/div/button/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>33e431aa-5d98-4f62-8774-a625d5896b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-medium text-colorTextLightMode dark:text-white bg-transparent nameMemberProfile</value>
      <webElementGuid>7101a925-3d7c-4934-ac11-d9cc9bcdf97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nga.nguyenthi</value>
      <webElementGuid>973c9304-6ee4-4502-84ba-b22ad76b1cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative&quot;]/div[@class=&quot;flex-col flex w-[272px] dark:bg-bgSecondary bg-[#F7F7F7] relative&quot;]/div[@class=&quot;flex-1 overflow-y-scroll font-medium text-gray-300 px-2 h-2/3 customSmallScrollLightMode&quot;]/div[@class=&quot;flex flex-col gap-1 text-[#AEAEAE] py-1 text-center relative&quot;]/button[@class=&quot;group text-[#AEAEAE] hover:text-white h-fit pl-2 rounded-[6px] dark:hover:bg-bgSecondary hover:bg-[#E1E1E1] py-2 w-full dark:focus:bg-bgTertiary focus:bg-[#c7c7c7]&quot;]/div[@class=&quot;relative group&quot;]/div[@class=&quot;relative gap-[5px] flex items-center cursor-pointer rounded   overflow-hidden&quot;]/div[@class=&quot;flex flex-col items-start&quot;]/p[@class=&quot;text-base font-medium text-colorTextLightMode dark:text-white bg-transparent nameMemberProfile&quot;]</value>
      <webElementGuid>05cbab7d-88e0-4e00-9111-07a8d6053809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[5]/div/button/div/div/div/p</value>
      <webElementGuid>c9605efd-1ad2-443d-9765-759d60c0925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friends'])[1]/following::p[2]</value>
      <webElementGuid>548537d0-7289-468c-a712-542bce63c4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM'])[1]/following::p[3]</value>
      <webElementGuid>04639f88-26e8-43ab-bb55-60a4250b3cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::p[1]</value>
      <webElementGuid>6f21f6f9-a14f-4048-91ec-4821e26e5820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friend'])[1]/preceding::p[3]</value>
      <webElementGuid>1901ee96-48e8-4b5b-9ee4-14d47b15f2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nga.nguyenthi']/parent::*</value>
      <webElementGuid>d18aa7d0-bc82-4d13-ac13-a457ff379d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div/p</value>
      <webElementGuid>a066e390-e629-43e8-ac31-dfa7e094c311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'nga.nguyenthi' or . = 'nga.nguyenthi')]</value>
      <webElementGuid>7f5a35f7-fab7-46c6-9ee0-afededd55495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
