<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header - Pin message btn</name>
   <tag></tag>
   <elementGuidId>8e675941-7fdb-4708-b0e7-421b9368d094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Settings'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > .w-fit > .focus-visible\:outline-none</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8b8ccbec-a269-4089-baf7-262c807c9c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9c3d9d9-78e2-4e51-ad0d-d8f7ec4de6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d921bfc-4b7b-430b-b179-55f1e891c44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e3654a9-f34d-4a5c-84da-a26167fa6e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e443ff3e-cb83-418a-95ae-6f871c6044f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7d72bea7-aee8-47d3-851f-8ab70d1b9c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>5f2ca869-1952-4181-b964-3643295559e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>726fa243-205c-4fbc-a80e-441185295a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:hover:text-white hover:text-black dark:text-white text-black</value>
      <webElementGuid>df51c312-f7be-4495-b0ee-eaf96fa802fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>69f874e7-094d-4eda-a70c-3d6e4875af9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen min-[480px]:pl-[72px]  overflow-hidden text-gray-100 relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-1 shrink min-w-0 gap-2&quot;]/div[@class=&quot;flex flex-col flex-1 shrink  min-w-0 bg-transparent h-[100%] overflow-visible&quot;]/div[@class=&quot;max-sbm:z-20 flex h-heightTopBar p-3 min-w-0 items-center flex-shrink dark:bg-bgPrimary bg-bgLightPrimary shadow-inner border-b-[1px] dark:border-bgTertiary border-bgLightTertiary false left-0&quot;]/div[@class=&quot;items-center h-full ml-auto flex&quot;]/div[@class=&quot;justify-end items-center gap-2 flex&quot;]/div[@class=&quot;hidden sbm:flex&quot;]/div[@class=&quot;relative justify-start items-center gap-[15px] flex mr-4&quot;]/div[@class=&quot;relative leading-5 h-5&quot;]/div[@class=&quot;w-fit&quot;]/button[@class=&quot;focus-visible:outline-none relative&quot;]/svg[@class=&quot;dark:hover:text-white hover:text-black dark:text-white text-black&quot;]</value>
      <webElementGuid>10641e2c-2cea-4dda-98d5-5401330180ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Settings'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e3645f8c-8709-483b-a48e-3fe3ce321926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Threads'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>4933a2ff-87f8-41ea-bfab-98e0ca44cdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned Messages'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>6841d4bb-5a4d-49c4-ba3b-dcfa24df4dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned Messages'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>97ec490f-b55b-43e5-843e-5c65e81cb93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
