<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>ecb81561-b5ad-4ed8-a797-dfa3bf0659b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div/div/div/div/div[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7104d813-574f-4740-ad11-863dc7cb01ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Text text-white hover:underline text-xs leading-normal font-semibold</value>
      <webElementGuid>cea57c37-38e2-4807-83fd-3a4b924f8d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>74c821c7-782f-4a33-b181-3e9765eeffcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;w-[100vw] h-[100vh] overflow-hidden fixed top-0 left-0 z-50 bg-black bg-opacity-80 flex flex-row justify-center items-center&quot;]/div[@class=&quot;z-60 w-full h-full sm:w-4/5 sm:max-h-[570px] md:w-[684px] bg-bgPrimary rounded-2xl flex-col justify-start  items-start gap-3 inline-flex&quot;]/div[@class=&quot;self-stretch md:h-96 flex-col justify-start items-start flex&quot;]/div[@class=&quot;self-stretch md:h-96 px-5 pt-8 flex-col justify-start items-start gap-3 flex&quot;]/div[@class=&quot;Frame394 relative border-t border-solid border-borderDefault self-stretch mb-0 pt-3 justify-end items-center gap-4 inline-flex&quot;]/button[@class=&quot;Text text-white hover:underline text-xs leading-normal font-semibold&quot;]</value>
      <webElementGuid>e3f48dc1-0868-4f47-ad8b-2f093495192a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div/div/div/div/div[5]/button</value>
      <webElementGuid>9332d720-f21c-4f33-aace-0e35060b6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only selected members and roles will be able to view this channel.'])[1]/following::button[1]</value>
      <webElementGuid>b638a28c-c535-4f28-9680-fc52d42c79c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is private channel?'])[1]/following::button[1]</value>
      <webElementGuid>b9c670ae-2718-4f58-8da2-c5665d31696b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Channel'])[1]/preceding::button[1]</value>
      <webElementGuid>517714af-99a0-4c85-a6a8-bab5ea56a29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[1]/preceding::button[2]</value>
      <webElementGuid>4b5832fd-615f-493a-a1a7-1e9d636d5ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>18360fa4-8f20-4753-8e6c-f3fce85c2bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>b1c2f6aa-e7da-4b20-8c3a-604c9266f8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>41e25e0c-b330-431b-9f8d-a37773253cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHANNELS'])[2]/preceding::button[2]</value>
      <webElementGuid>8d69ce7c-4b99-456b-9190-510a209e7f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
