<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What is channel, , s name)_Inp_00fae1</name>
   <tag></tag>
   <elementGuidId>7cb54a59-0528-4d3d-8a8d-d94168eff954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>258881cb-9f00-47a2-946d-db65b22372c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]</value>
      <webElementGuid>c84d2209-40ba-41f7-9101-d4c912137cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the channel's name</value>
      <webElementGuid>ca3a1094-822e-4ff6-adab-2cc40d0c1f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channelList&quot;)/div[@class=&quot;w-[100vw] h-[100vh] overflow-hidden fixed top-0 left-0 z-50 bg-black bg-opacity-80 flex flex-row justify-center items-center&quot;]/div[@class=&quot;z-60 w-full h-full sm:w-4/5 sm:max-h-[570px] md:w-[684px] bg-bgPrimary rounded-2xl flex-col justify-start  items-start gap-3 inline-flex&quot;]/div[@class=&quot;self-stretch md:h-96 flex-col justify-start items-start flex&quot;]/div[@class=&quot;self-stretch md:h-96 px-5 pt-8 flex-col justify-start items-start gap-3 flex&quot;]/div[@class=&quot;Frame408 self-stretch h-[84px] flex-col justify-start items-start gap-2 flex mt-1&quot;]/div[@class=&quot;ContentContainer self-stretch h-11 flex-col items-start flex&quot;]/div[@class=&quot;InputContainer self-stretch h-11 px-4 py-3 bg-neutral-950 rounded shadow border w-full border-blue-600  justify-start items-center gap-2 inline-flex&quot;]/div[@class=&quot;InputValue grow shrink basis-0 self-stretch justify-start items-center flex&quot;]/input[@class=&quot;Input grow shrink basis-0 h-10 outline-none bg-neutral-950 text-neutral-200 text-sm font-normal placeholder-[#AEAEAE]&quot;]</value>
      <webElementGuid>6046cd1b-82cd-42f1-a069-3ff1a8d82868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='channelList']/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>aee42604-517b-4216-b41a-52e084997cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>41894890-2fb5-48d1-a197-724df96af1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = concat(&quot;Enter the channel&quot; , &quot;'&quot; , &quot;s name&quot;)]</value>
      <webElementGuid>25621663-b9c1-4472-aaa4-a3baaeaa8901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
