<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Forward option</name>
   <tag></tag>
   <elementGuidId>0c16bc29-bf9b-4fe0-8460-0dfca9f8c33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainChat&quot;]/div/div/div[1]/div[2]/div[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec0d9c8a-274c-40ac-8e93-c9fd57e39bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> dark:text-[#ADB3B9] text-[#4E5058] hover:text-[#FFFFFF] dark:hover:text-[#FFFFFF]  p-1</value>
      <webElementGuid>946daf40-f4b4-42b8-a0bd-88ba26a05e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forward Message </value>
      <webElementGuid>3f5a8fc3-2e0a-453a-9bc5-61cc664aadbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;relative dark:bg-bgPrimary max-w-widthMessageViewChat bg-bgLightPrimary h-heightMessageViewChat&quot;]/div[@class=&quot;contexify z-50 contexify_willEnter-fade&quot;]/div[@class=&quot;contexify_item&quot;]/div[@class=&quot;contexify_itemContent&quot;]/div[@class=&quot;dark:text-[#ADB3B9] text-[#4E5058] hover:text-[#FFFFFF] dark:hover:text-[#FFFFFF]  p-1&quot;]</value>
      <webElementGuid>260e4d91-8ed6-42b9-ad1b-81895ffbdae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div/div[2]/div[13]/div/div</value>
      <webElementGuid>0d80f98d-467e-4100-8195-efd1b33e5dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Message Link'])[1]/following::div[3]</value>
      <webElementGuid>8aedceb9-282b-4c8c-95b9-9a85d567b062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark Unread'])[1]/following::div[6]</value>
      <webElementGuid>f52b1ba2-146f-48cd-bc92-f1a613812480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speak Message'])[1]/preceding::div[1]</value>
      <webElementGuid>b0fc20e2-e606-4c81-9638-53a9a7adfaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[13]/div/div</value>
      <webElementGuid>e2918717-0121-454e-a72a-12ae56b1ca12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Forward Message ' or . = 'Forward Message ')]</value>
      <webElementGuid>422d5d62-6e82-4af4-9c97-5c8cf3e29235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
