<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_private_reply</name>
   <tag></tag>
   <elementGuidId>663dc3af-b5ed-40a4-a415-01883a8d3de9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div/div[2]/div[7]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fd9e544-d0d5-462f-9206-6e0785675829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> dark:text-[#ADB3B9] text-[#4E5058] hover:text-[#FFFFFF] dark:hover:text-[#FFFFFF]  p-1</value>
      <webElementGuid>e5ff044a-c1d1-4f6f-a888-04127c16f30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reply </value>
      <webElementGuid>f11e501d-c10f-4409-bebe-690f80d384e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;relative dark:bg-bgPrimary max-w-widthMessageViewChat bg-bgLightPrimary h-heightMessageViewChat&quot;]/div[@class=&quot;contexify z-50 contexify_willEnter-fade&quot;]/div[@class=&quot;contexify_item&quot;]/div[@class=&quot;contexify_itemContent&quot;]/div[@class=&quot;dark:text-[#ADB3B9] text-[#4E5058] hover:text-[#FFFFFF] dark:hover:text-[#FFFFFF]  p-1&quot;]</value>
      <webElementGuid>2cc0a158-9ef1-4f58-94db-52bc961e1ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div/div[2]/div[7]/div/div</value>
      <webElementGuid>771e75c8-0ced-41f5-83db-ed697365b9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add To Note'])[1]/following::div[3]</value>
      <webElementGuid>a795ddb1-80dc-43f9-b087-8911aba175ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin Message'])[1]/following::div[6]</value>
      <webElementGuid>0291b304-82e2-4948-8d94-075cf37efce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Thread'])[1]/preceding::div[1]</value>
      <webElementGuid>718c6e5e-739f-4223-8b7e-ab71fe9fdcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div</value>
      <webElementGuid>818fa61e-7c7a-4cae-b44d-a493d9fa9394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reply ' or . = 'Reply ')]</value>
      <webElementGuid>ba4ce351-2223-49c6-81e6-d1ab21231060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
