<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Message forwarded successfully</name>
   <tag></tag>
   <elementGuidId>3bfe5cc0-40b0-4665-a561-89107060b202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1732761263375</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app-layout&quot;]/div[1]/div/div[@class=&quot;Toastify__toast--success&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecd4fc1b-372f-477e-a466-3f79186c107f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1732761263375</value>
      <webElementGuid>80e50999-08c6-473f-8f83-ad6322255a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--light Toastify__toast--success Toastify__toast--close-on-click</value>
      <webElementGuid>c8789f41-4aea-43c4-95b2-d78e29e4912e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message forwarded successfully</value>
      <webElementGuid>ae6b71f8-b937-43f5-a2b6-2764de5fd2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1732761263375&quot;)</value>
      <webElementGuid>c3b18593-4228-4a12-ad8c-db8d247d4c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1732761263375']</value>
      <webElementGuid>4c19d675-1b94-4d06-b51c-1697109c987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-layout']/div/div/div</value>
      <webElementGuid>854315df-3682-4266-a454-c58653d42676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading ...'])[1]/following::div[5]</value>
      <webElementGuid>9ae97ce3-f869-4b6d-bb73-7267a208b186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>cafca71a-dd84-4802-9485-eed1e769ee52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1732761263375' and (text() = 'Message forwarded successfully' or . = 'Message forwarded successfully')]</value>
      <webElementGuid>4aa3adbf-2ed8-46fc-b5d5-36c01a2b3676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
