<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_private_options</name>
   <tag></tag>
   <elementGuidId>1b377863-2d91-4d91-b904-2a28ffbc66db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::*[name()='svg'][5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ca6ec6b7-fee9-4ff6-9910-40f0469b4483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>e0266c7d-0fa1-4212-87eb-286d7c356a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e0d5d730-51c1-4d77-bf67-21496139638f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a6e680cf-772c-437c-a796-6b1f7449d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 dark:text-[#B5BAC1] text-colorTextLightMode dark:hover:text-white hover:text-black</value>
      <webElementGuid>c0785ca7-fa69-49f1-8540-a36550f6694d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollLoading&quot;)/div[2]/div[1]/div[1]/div[@class=&quot;fullBoxText relative group pt-3&quot;]/div[2]/div[@class=&quot;chooseForText z-[1] absolute h-8 p-0.5 rounded block -top-5 top-4 right-6 w-fit&quot;]/div[@class=&quot;flex justify-between dark:bg-bgDarkPopover bg-bgLightMode border border-bgSecondary rounded&quot;]/div[@class=&quot;w-fit h-full flex items-center justify-between&quot;]/button[@class=&quot;h-full p-1 cursor-pointer popup-btn&quot;]/svg[@class=&quot;w-5 h-5 dark:text-[#B5BAC1] text-colorTextLightMode dark:hover:text-white hover:text-black&quot;]</value>
      <webElementGuid>9d0fd61c-a525-4c87-92fe-5aa43d9e03df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>d2468844-1370-40af-b644-3bf2ce9cfbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today at 18:25'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>de3b978f-5fb2-411c-8f40-48e59741e72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
