<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Replying to</name>
   <tag></tag>
   <elementGuidId>bcc35fcf-9639-495c-9d8b-af76b20e59fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c83359c2-9bbf-450b-8fe0-ab1ab3565820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-row items-center justify-between w-full dark:bg-[#2B2D31] bg-bgLightMode p-2 rounded-md text-[14px] pb-[15px]</value>
      <webElementGuid>2829c881-36da-4954-bb6e-07834214c11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Replying to geBXclVQui</value>
      <webElementGuid>5e9aff3d-d712-40bd-887a-c5f58c16b2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;relative z-1 pb-[4px]&quot;]/div[@class=&quot;flex flex-row items-center justify-between w-full dark:bg-[#2B2D31] bg-bgLightMode p-2 rounded-md text-[14px] pb-[15px]&quot;]</value>
      <webElementGuid>6726c777-df1b-4bd8-81d8-f4e792669e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>b4940bb8-26ca-4924-827b-dceed1ab6149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='he lo mn'])[14]/following::div[9]</value>
      <webElementGuid>95c1b1a4-7f17-4257-883e-dd6a469375a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ae oiiiiii'])[5]/following::div[29]</value>
      <webElementGuid>e6c2f17c-b916-49f5-86d5-169d271b37d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>0af5fdcf-68f3-4dea-8b4b-76dea5606690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Replying to geBXclVQui' or . = 'Replying to geBXclVQui')]</value>
      <webElementGuid>8e45b761-4b1c-4ef0-a650-fd47c6733f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
