<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_general_checkbox-item to forward</name>
   <tag></tag>
   <elementGuidId>1b93968f-40e6-43fe-8dcf-9036fe81e03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-item-1810967355170230272</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;checkbox-item-1813129510904664064&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d70ff8a4-4543-443b-bc75-59b596041785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ac1412d3-7461-416a-bd9d-7adc02521e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 focus:ring-transparent</value>
      <webElementGuid>2a835372-310a-4e45-8730-362741227d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-item-1810967355170230272</value>
      <webElementGuid>6d53cb07-85b6-4473-a5c0-f49bfbc6fedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-item-1810967355170230272&quot;)</value>
      <webElementGuid>57f02d99-f1bf-42da-8690-e70c8025109f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-item-1810967355170230272']</value>
      <webElementGuid>8857e86c-37f2-46ce-9ab5-7d75755783b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r2k:']/div/div/div[2]/div/div/input</value>
      <webElementGuid>3b238a30-c71f-48ab-86ff-ac9b290a2926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>3179965f-b7f2-4d44-b2b9-226d7c57ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox-item-1810967355170230272']</value>
      <webElementGuid>9e3263b7-a415-4596-9e3b-f8f9ee4dbd39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
