<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Emojis pannel</name>
   <tag></tag>
   <elementGuidId>2098e857-91cf-4566-8c78-4e6de3e28ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainChat&quot;]/div/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Gifs Stickers Emoji Find the perfect emoji KOMU_2 08-08-24 Recent Frequency :logok: :froge_camera: :froge: spbell :melon: :tiger: :ewwwW: :7226885252132198440: :cam_sung: :1708940817973: :Logo: :grin: :truck: :flag_ai: :apple: :froge_camera: :rofl: :96074-clydeheart: :image123456: :loa: KOMU_2 08-08-24 :Froge_pvp: :froge_confused: :Froge_Mahahah: :froge_confused: :froge_stonkssss: :froge_fightt: People :wink: :upside_down: :sweat_smile: :smiling_tear: :smiley: :smile: :slight_smile: :relieved: :relaxed: :like: :laughing: :joy: :innocent: :heart_eyes: :grinning: :face_tears: :blush: :100: Nature :see_no_evil: :rabbit: :polar_bear: :pig_nose: :pig: :panda_face: :mouse: :monkey_face: :lion_face: :koala: :hamster: :frog: :fox: :dog: :cow: :cat: :bear: Food :watermelon: :tomato: :tangerine: :strawberry: :pineapple: :pear: :peach: :mango: :lemon: :kiwi: :green_apple: :grapes: :coconut: :cherries: :blueberries: :banana: Activities :yo_yo: :volleyball: :tennis: :softball: :soccer: :rugby_football: :ping_pong: :lacrosse: :hockey: :football: :flying_disc: :field_hockey: :eightball: :cricket_game: :boomerang: :basketball: :baseball: :badminton: Travel :trolleybus: :tractor: :taxi: :red_car: :race_car: :probing_cane: :police_car: :pickup_truck: :motorized_wheelchair: :minibus: :manual_wheelchair: :fire_engine: :crutch: :bus: :blue_car: :articulated_lorry: :ambulance: Objects :watch: :vhs: :trackball: :printer: :mouse_three_button: :mobile_phone: :minidisc: :keyboard: :joystick: :floppy_disk: :dvd: :desktop: :computer: :compression: :cd: :camera_with_flash: :camera: :calling: Symbols :yellow_heart: :white_heart: :two_hearts: :revolving_hearts: :purple_heart: :pink_heart: :orange_heart: :light_blue_heart: :heartpulse: :heartbeat: :heart_exclamation: :heart: :grey_heart: :green_heart: :brown_heart: :broken_heart: :blue_heart: :black_heart: Flags :united_nations: :tria_fg_post: :transgender_fg: :rainbow_flag: :pirate_flag: :flag_white: :flag_dz: :flag_black: :flag_ax: :flag_as: :flag_aq: :flag_ao: :flag_al: :flag_ag: :flag_af: :flag_ad: :checkered_flag: Write your thoughts here...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8e8989e6-5927-4cc6-910c-5227193cd234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:hover:text-white hover:text-black w-6 h-6 dark:text-white text-black</value>
      <webElementGuid>988b8c18-f1eb-415f-b82c-fb7d2986ff43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>285e696e-a433-4d99-b73b-46ef558ef581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>565c591d-e796-4154-abcb-49b936f486da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>6138b619-9ae6-4552-84b9-2e7fce250f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>ff69bb0f-0253-4a0f-a3c7-4a368139d214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>e13029ea-be79-45d2-8020-3560c259e3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>1eec79fa-ed30-45aa-848a-a740b0339f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;relative max-sm:-pb-2&quot;]/div[@class=&quot;flex flex-inline items-start gap-2 box-content mb-4 max-sm:mb-0
				 dark:bg-channelTextarea bg-channelTextareaLight rounded-lg relative rounded-t-lg
				  w-wrappBoxChatView&quot;]/div[@class=&quot;w-full dark:bg-channelTextarea bg-channelTextareaLight gap-3 flex items-center rounded-e-md&quot;]/div[@class=&quot;w-full rounded-r-lg dark:bg-channelTextarea bg-channelTextareaLight gap-3 relative whitespace-pre-wrap&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex flex-row absolute h-11 items-center gap-1 mr-3 top-0 right-0&quot;]/div[@class=&quot;w-6 h-6&quot;]/svg[@class=&quot;dark:hover:text-white hover:text-black w-6 h-6 dark:text-white text-black&quot;]</value>
      <webElementGuid>3236004c-94b0-428e-b53a-61ae3a606952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emoji'])[1]/following::*[name()='svg'][28]</value>
      <webElementGuid>a3cfba6b-22f1-4e67-a92f-b0ade34e1f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stickers'])[1]/following::*[name()='svg'][28]</value>
      <webElementGuid>445f3a05-9e00-48b4-96da-af5b1a176937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
