<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nga Nguyen Thi</name>
   <tag></tag>
   <elementGuidId>46f6217e-2136-4cd1-bdad-a82cdf44bfda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[2]/div[3]/div/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aab678b9-1885-4f90-87ed-f169c9df67c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group/itemListDm relative  text-[#AEAEAE] hover:text-white h-fit pl-2 rounded-[6px] dark:hover:bg-[rgba(30,30,30,0.4)] hover:bg-[#E1E1E1] py-2 w-full dark:focus:bg-bgTertiary focus:bg-[#c7c7c7] </value>
      <webElementGuid>49d07b02-4b8c-4700-8f72-ab8ef4713c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nga Nguyen Thi</value>
      <webElementGuid>6f06ff07-eb8f-468c-8cf3-524d07163a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen min-[480px]:pl-[72px]  overflow-hidden text-gray-100 relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex-col  flex w-[272px] dark:bg-bgSecondary bg-bgLightMode relative min-w-widthMenuMobile  sbm:min-w-[272px]&quot;]/div[@class=&quot;flex-1 font-medium text-gray-300 px-2 h-2/3 thread-scroll&quot;]/div[@class=&quot;flex flex-col gap-1 text-[#AEAEAE] text-center relative&quot;]/div[@class=&quot;custom-member-list thread-scroll&quot;]/div[1]/div[3]/div[@class=&quot;group/itemListDm relative  text-[#AEAEAE] hover:text-white h-fit pl-2 rounded-[6px] dark:hover:bg-[rgba(30,30,30,0.4)] hover:bg-[#E1E1E1] py-2 w-full dark:focus:bg-bgTertiary focus:bg-[#c7c7c7]&quot;]</value>
      <webElementGuid>2d7a10c2-9d63-4b54-bfcf-2aa4298b7b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[3]/div/div/div/div[3]/div</value>
      <webElementGuid>ebdfbb6c-36fb-47da-9254-d76175880056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nga nguyễn'])[1]/following::div[2]</value>
      <webElementGuid>7060fa3e-08b3-49a3-a5a1-6ac7750a105d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minh 1 Nguyen Van'])[1]/following::div[11]</value>
      <webElementGuid>6e86570d-6739-4757-b6df-05d203557401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nga Nguyen Thi,Nga nguyễn'])[1]/preceding::div[28]</value>
      <webElementGuid>e0f62747-8dbf-48bb-bc19-5e0470c836bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[3]/div</value>
      <webElementGuid>23df071d-d0a4-4ffa-92d3-785cad6f1663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nga Nguyen Thi' or . = 'Nga Nguyen Thi')]</value>
      <webElementGuid>8e530032-1a23-4f39-9276-18b55962428f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
