<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emoji-on-the-thread</name>
   <tag></tag>
   <elementGuidId>1da868b2-cff7-499f-ba43-d88ae6a2dfac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg-1840651252715753472']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#msg-1840651252715753472 >> internal:role=img[name=&quot;message&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1972e928-ddff-4fe0-a354-fff3182e3e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> flex object-cover object-left-top rounded cursor-default </value>
      <webElementGuid>44b93806-b78d-4326-be74-2af858a59e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.mezon.vn/stickers/Custom/1813095696169963520/1819297236786352128/1788103935005823000/10Froge_pvp.gif</value>
      <webElementGuid>c3cda7bb-ce0d-4672-b59d-2f04df834871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>dac04b3a-33eb-49d9-a641-3863799eb6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-1840651252715753472&quot;)/div[@class=&quot;relative rounded-sm overflow-visible&quot;]/div[@class=&quot;flex h-15 flex-col w-auto px-3&quot;]/div[@class=&quot;justify-start gap-4 inline-flex w-full relative h-fit overflow-visible pr-12&quot;]/div[@class=&quot;w-full relative h-full&quot;]/div[@class=&quot;justify-start items-center  inline-flex w-full h-full pt-[2px] textChat select-text&quot;]/div[@class=&quot;flex flex-col whitespace-pre-wrap text-base w-full cursor-text&quot;]/div[@class=&quot;flex flex-row justify-start flex-wrap w-full gap-x-2&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;my-1&quot;]/div[@class=&quot;flex&quot;]/img[@class=&quot;flex object-cover object-left-top rounded cursor-default&quot;]</value>
      <webElementGuid>15c20a4d-b876-4dfc-918d-58cfd18c8c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg-1840651252715753472']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>37f642d4-5949-4b66-9239-16d46b4890c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='message'])[10]</value>
      <webElementGuid>7d2c311a-ff02-4276-8679-adfc69cbb7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>0e91c365-e9a2-43cc-b7b2-546d525cd6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.mezon.vn/stickers/Custom/1813095696169963520/1819297236786352128/1788103935005823000/10Froge_pvp.gif' and @alt = 'message']</value>
      <webElementGuid>5ca82b59-dbb1-41c4-b185-7d477298c723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
