<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gif_display_onscreen</name>
   <tag></tag>
   <elementGuidId>9b6a0fc7-59ef-422f-b51f-3b1ba335f8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg-1840651252686393344']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#msg-1840651252686393344 >> internal:role=img[name=&quot;message&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f7ee59f4-1b20-43f5-b15a-6ab9c62ffb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> flex object-cover object-left-top rounded cursor-default </value>
      <webElementGuid>c663c5d4-e0b0-4f6d-ac5a-822faf318feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.tenor.com/0dc7tgGjf6gAAAAC/peach-goma-peach.gif</value>
      <webElementGuid>5050e22b-cebd-49b5-b82c-eee72d29c441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>6f98a94a-0757-4cb9-9255-f79520fe4a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-1840651252686393344&quot;)/div[@class=&quot;relative rounded-sm overflow-visible&quot;]/div[@class=&quot;flex h-15 flex-col w-auto px-3&quot;]/div[@class=&quot;justify-start gap-4 inline-flex w-full relative h-fit overflow-visible pr-12&quot;]/div[@class=&quot;w-full relative h-full&quot;]/div[@class=&quot;justify-start items-center  inline-flex w-full h-full pt-[2px] textChat select-text&quot;]/div[@class=&quot;flex flex-col whitespace-pre-wrap text-base w-full cursor-text&quot;]/div[@class=&quot;flex flex-row justify-start flex-wrap w-full gap-x-2&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;my-1&quot;]/div[@class=&quot;flex&quot;]/img[@class=&quot;flex object-cover object-left-top rounded cursor-default&quot;]</value>
      <webElementGuid>e8e50081-9031-4461-aafd-b8ea66f37cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg-1840651252686393344']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>2ff7894a-60f0-43a7-8e90-54c5c4c051b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='message'])[8]</value>
      <webElementGuid>c84fa168-3469-4188-ab6c-3f82b836c797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>369e79bf-1d14-42fc-a4cd-1ac44c24fbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.tenor.com/0dc7tgGjf6gAAAAC/peach-goma-peach.gif' and @alt = 'message']</value>
      <webElementGuid>83e70e80-c1d3-4145-b175-d734c36aa087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
