<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gifs_pannel</name>
   <tag></tag>
   <elementGuidId>6ba33ecb-6093-4561-b308-39800a4533eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f51073ed-450f-4a96-b6c2-33a3bc3ac073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 border-2 border-blue-500 opacity-0 group-hover:opacity-100 transition-opacity rounded-md z-30</value>
      <webElementGuid>d974dd7d-82cb-463d-bade-690413f40f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;right-[2px] absolute z-10 origin-bottom-right&quot;]/div[@class=&quot;w-[370px] max-sm:w-full max-sm:pt-0 max-sm:rounded-none max-sm:mt-[-0.5rem]
			sbm:w-[500px] max-sbm:w-[312px] max-sbm:rounded-lg h-fit rounded-lg dark:bg-bgSecondary bg-bgLightMode shadow shadow-neutral-900 z-30
			 min-h-[500px]&quot;]/div[@class=&quot;w-full min-h-[400px] text-center md:w-[500px]&quot;]/div[@class=&quot;flex h-full pr-1 w-full md:w-[500px]&quot;]/div[@class=&quot;outline-none&quot;]/div[@class=&quot;mx-2 grid grid-cols-2 justify-center h-[400px] overflow-y-scroll hide-scrollbar gap-2&quot;]/div[@class=&quot;relative h-32 rounded-md cursor-pointer overflow-hidden group&quot;]/div[@class=&quot;absolute inset-0 border-2 border-blue-500 opacity-0 group-hover:opacity-100 transition-opacity rounded-md z-30&quot;]</value>
      <webElementGuid>0970b19e-3daf-417a-b62f-707e7decf7ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>e4f2f4f8-54d9-41d5-8bb2-1dd317d4d08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>94e1f986-ca9a-4a63-8f6b-468960e1af64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
