<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Emoji_w-full h-full aspect-square object-cover cursor-pointer darkhoverbg-bgDisable hoverbg-bgLightModeButton hoverrounded-lg border border-bgHoverMember rounded-lg</name>
   <tag></tag>
   <elementGuidId>81662856-09c9-4fad-a3dd-1bbcdf550c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;sticker&quot;i] >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0c200e8-94a8-438a-8c44-720ff5f0bfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.mezon.vn/stickers/Custom/1813095696169963520/1819297236786352128/1788103935005823000/10Froge_pvp.gif</value>
      <webElementGuid>75292ae9-f34f-4e5c-a56e-008f87ddaa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sticker</value>
      <webElementGuid>85a300f6-fa90-448d-b108-a3a974ce8e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-full aspect-square object-cover cursor-pointer dark:hover:bg-bgDisable hover:bg-bgLightModeButton hover:rounded-lg border border-bgHoverMember rounded-lg</value>
      <webElementGuid>8dc1dafd-fda4-41a1-b580-4738cbf48f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1264e63a-c92e-44f7-8bf1-c97610223d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;right-[2px] absolute z-10 animate-scale_up origin-bottom-right&quot;]/div[@class=&quot;w-[370px] max-sm:w-full max-sm:pt-0 max-sm:rounded-none max-sm:mt-[-0.5rem]
			sbm:w-[500px] max-sbm:w-[312px] max-sbm:rounded-lg h-fit rounded-lg dark:bg-bgSecondary bg-bgLightMode shadow shadow-neutral-900 z-30
			 min-h-[500px]&quot;]/div[@class=&quot;w-full min-h-[400px] text-center md:w-[500px]&quot;]/div[@class=&quot;flex h-full pr-2 w-full md:w-[500px]&quot;]/div[@class=&quot;outline-none flex h-full w-full md:w-[500px] max-sm:ml-1&quot;]/div[@class=&quot;flex flex-col h-[400px] overflow-y-auto flex-1 hide-scrollbar&quot;]/div[2]/div[1]/div[@class=&quot;w-auto pb-2 px-2&quot;]/div[@class=&quot;grid grid-cols-3 gap-4 max-h-[400px] overflow-y-scroll hide-scrollbar&quot;]/img[@class=&quot;w-full h-full aspect-square object-cover cursor-pointer dark:hover:bg-bgDisable hover:bg-bgLightModeButton hover:rounded-lg border border-bgHoverMember rounded-lg&quot;]</value>
      <webElementGuid>47c3854e-d34f-41f4-90cb-44d52fe16a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>f9c71273-13df-42f0-8629-40f7db56abd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='sticker'])[2]</value>
      <webElementGuid>5cd2cd51-d4f3-436a-9dc6-0053a7797900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>a66f9515-786c-4b1b-b4a1-dbd7d75d0e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.mezon.vn/stickers/Custom/1813095696169963520/1819297236786352128/1788103935005823000/10Froge_pvp.gif' and @alt = 'sticker']</value>
      <webElementGuid>8f0f6ed3-cf62-4e5f-9fb1-72815fd12ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
