<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Emoji_max-h-full max-w-full</name>
   <tag></tag>
   <elementGuidId>bc2bf7e0-a3c3-4202-930f-d2357cd9c602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-layout']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[4]/div/div/button[6]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe98590f-2b5c-405d-857d-e5d5ed985f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d532ca7a-ea6f-4888-8600-1696142b9bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.mezon.vn/emojis/7228669359607528642.webp</value>
      <webElementGuid>00c48c81-92f2-4331-9fdc-4af3e0a8a883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>:froge_fightt:</value>
      <webElementGuid>a0372ec6-b320-42ca-ac4a-3b42cecd72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-full max-w-full</value>
      <webElementGuid>e8086c2a-6f76-471d-bf02-028df0db3c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen min-[480px]:pl-[72px]  overflow-hidden text-gray-100 relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-col
			 flex-1 shrink min-w-0 bg-transparent
				h-[100%] overflow-visible&quot;]/div[@class=&quot;flex flex-row flex-1 w-full&quot;]/div[@class=&quot;flex-col flex-1 h-full max-h-messageViewChatDM w-full flex&quot;]/div[@class=&quot;flex-shrink-0 flex flex-col z-0 dark:bg-bgPrimary bg-bgLightPrimary h-auto relative&quot;]/div[@class=&quot;mx-2 relative&quot;]/div[@class=&quot;right-[2px] absolute z-10&quot;]/div[@class=&quot;w-[370px] max-sm:w-full max-sm:pt-0 max-sm:rounded-none max-sm:mt-[-0.5rem]
			sbm:w-[500px] max-sbm:w-[312px] max-sbm:rounded-lg h-fit rounded-lg dark:bg-bgSecondary bg-bgLightMode shadow shadow-neutral-900 z-30
			 min-h-[500px]&quot;]/div[@class=&quot;w-full min-h-[400px] text-center md:w-[500px]&quot;]/div[@class=&quot;flex h-full pr-2 w-full sbm:w-[312px] md:w-[500px]&quot;]/div[@class=&quot;outline-none flex max-h-full max-sm:h-32 max-sbm:h-full flex-row w-full md:w-[500px] max-sm:ml-1 undefined&quot;]/div[@class=&quot;flex flex-col w-[90%] pr-2&quot;]/div[@class=&quot;w-full  max-h-[352px] overflow-y-scroll pt-0 overflow-x-hidden hide-scrollbar dark: bg-transparent bg-bgLightMode&quot;]/div[@class=&quot;w-full&quot;]/div[1]/div[@class=&quot;grid grid-cols-9 ml-1 gap-1&quot;]/button[@class=&quot;text-2xl  emoji-button  rounded-md  dark:hover:bg-[#41434A] hover:bg-bgLightModeButton hover:rounded-md  p-1 flex items-center justify-center w-full aspect-square&quot;]/img[@class=&quot;max-h-full max-w-full&quot;]</value>
      <webElementGuid>b7a0066f-6ebe-4d2f-bff1-bc17d08856b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[4]/div/div/button[6]/img</value>
      <webElementGuid>e5e75698-5ef0-46a3-86e9-cbdd19e6da59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=':froge_fightt:']</value>
      <webElementGuid>e53c7fe1-a69b-48c8-9bb8-d52452d3bb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button[6]/img</value>
      <webElementGuid>7e85770d-aac6-48e1-9d13-f909225fe221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.mezon.vn/emojis/7228669359607528642.webp' and @alt = ':froge_fightt:']</value>
      <webElementGuid>916634bd-2df7-4af0-8727-cd59a0ca55d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
