<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_gif_in_gif_panal</name>
   <tag></tag>
   <elementGuidId>d14a44cd-dee0-4c35-9a4f-3dbaa15d3b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-full.h-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15b03597-8c79-4398-9b1b-41eed43272af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif</value>
      <webElementGuid>242f3a64-8acd-4e57-b740-f266385154df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif</value>
      <webElementGuid>ac23a3b4-19a3-4454-b786-6bc98a2a4942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto</value>
      <webElementGuid>054572a9-5708-4183-a49b-244eb5369c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex flex-row h-heightWithoutTopBar&quot;]/div[@class=&quot;flex flex-col flex-1 min-w-60 w-widthThumnailAttachment h-full false z-10&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightPrimary h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;right-[2px] absolute z-10 origin-bottom-right&quot;]/div[@class=&quot;w-[370px] max-sm:w-full max-sm:pt-0 max-sm:rounded-none max-sm:mt-[-0.5rem]
			sbm:w-[500px] max-sbm:w-[312px] max-sbm:rounded-lg h-fit rounded-lg dark:bg-bgSecondary bg-bgLightMode shadow shadow-neutral-900 z-30
			 min-h-[500px]&quot;]/div[@class=&quot;w-full min-h-[400px] text-center md:w-[500px]&quot;]/div[@class=&quot;flex h-full pr-1 w-full md:w-[500px]&quot;]/div[@class=&quot;outline-none&quot;]/div[@class=&quot;mx-2 flex justify-center h-[400px] overflow-y-scroll hide-scrollbar flex-wrap&quot;]/div[@class=&quot;grid grid-cols-3  gap-1&quot;]/div[@class=&quot;order-0 overflow-hidden cursor-pointer&quot;]/img[@class=&quot;w-full h-auto&quot;]</value>
      <webElementGuid>11e5bd1a-180b-4ca0-b235-58ca61f69cd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainChat']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>36cbd7ab-53d3-4804-bd22-a0fb1e015041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif']</value>
      <webElementGuid>f9d380c9-0f02-4a84-b9c0-69f5cbdd93fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>84046ee6-0b4d-466f-8148-5f0a40a48a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif' and @alt = 'https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif']</value>
      <webElementGuid>320bf502-b765-465e-a2bf-9be4a0ec1f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
