<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_msg_gif_after_sent</name>
   <tag></tag>
   <elementGuidId>4d8bf5af-4d50-402e-a471-84731acd945d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg-1840651252757696512']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e27e2f93-29a6-4f85-bbbe-f7dfb3625e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> flex object-cover object-left-top rounded cursor-default </value>
      <webElementGuid>aa020fa9-88fb-416d-a39b-73591d88d3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif</value>
      <webElementGuid>a225c510-3317-4cd1-b34d-7011b0374b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>0f745818-705c-4393-9817-37793d906a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-1840651252757696512&quot;)/div[@class=&quot;relative rounded-sm overflow-visible&quot;]/div[@class=&quot;flex h-15 flex-col w-auto px-3&quot;]/div[@class=&quot;justify-start gap-4 inline-flex w-full relative h-fit overflow-visible pr-12&quot;]/div[@class=&quot;w-full relative h-full&quot;]/div[@class=&quot;justify-start items-center  inline-flex w-full h-full pt-[2px] textChat select-text&quot;]/div[@class=&quot;flex flex-col whitespace-pre-wrap text-base w-full cursor-text&quot;]/div[@class=&quot;flex flex-row justify-start flex-wrap w-full gap-x-2&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;my-1&quot;]/div[@class=&quot;flex&quot;]/img[@class=&quot;flex object-cover object-left-top rounded cursor-default&quot;]</value>
      <webElementGuid>39feedaf-89dd-43d9-8ab3-dcae10af8f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg-1840651252757696512']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>e00a3bc1-8021-44b3-8f07-43defa04b5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='message'])[7]</value>
      <webElementGuid>2ee3e2c6-f9f4-4215-acd2-f6ecdcdbb6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>a0579f20-8c9e-4bc0-8813-dfa5d8a689e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.tenor.com/winFVKQMg00AAAAC/brutus-bucks.gif' and @alt = 'message']</value>
      <webElementGuid>69ae5a74-974f-4220-a862-b0b4ca7700ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
