<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_emoji</name>
   <tag></tag>
   <elementGuidId>c9decb8c-3459-42e6-b65f-2327374ae3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//path[@fill='currentColor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>f3c040d3-9f16-42d3-9f65-3f676f7904c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>66c13346-aa7d-4749-9ef8-2529081dd556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>07251590-92a6-4062-ad6e-87cf5c8724a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M12 23a11 11 0 1 0 0-22 11 11 0 0 0 0 22ZM6.5 13a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm11 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm-9.8 1.17a1 1 0 0 1 1.39.27 3.5 3.5 0 0 0 5.82 0 1 1 0 0 1 1.66 1.12 5.5 5.5 0 0 1-9.14 0 1 1 0 0 1 .27-1.4Z</value>
      <webElementGuid>b4946fb8-a4f6-465f-9dca-b63b8e62eade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>5eab41ad-b308-4528-a9c4-c52ed78fbfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainChat&quot;)/div[@class=&quot;flex h-heightWithoutTopBar flex-row&quot;]/div[@class=&quot;flex flex-col flex-1 w-widthMessageViewChat h-full false&quot;]/div[@class=&quot;flex-shrink flex flex-col dark:bg-bgPrimary bg-bgLightModeSecond h-auto relative w-full&quot;]/div[@class=&quot;mx-4 relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex flex-inline items-center gap-2 box-content mb-4 dark:bg-channelTextarea bg-bgLightMode rounded-lg relative rounded-t-lg max-w-wrappBoxChatView&quot;]/div[@class=&quot;w-full dark:bg-channelTextarea bg-bgLightMode gap-3 flex items-center rounded-e-md&quot;]/div[@class=&quot;flex flex-row h-full items-center gap-1 w-18 mr-3 absolute right-0&quot;]/div[@class=&quot;cursor-pointer&quot;]/svg[@class=&quot;dark:hover:text-white hover:text-black w-6 h-6 dark:text-[#B5BAC1] text-colorTextLightMode&quot;]/path[1]</value>
      <webElementGuid>81931536-bb7c-40e1-ba53-b204e2f9a866</webElementGuid>
   </webElementProperties>
</WebElementEntity>
