<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sticker_after_sent_to_channel_chat</name>
   <tag></tag>
   <elementGuidId>19cdf448-9172-4959-a89c-1a87775fd72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg-1840651252774473728']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>88f4b2d7-abd6-4ae2-b4a7-76683f937dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> flex object-cover object-left-top rounded cursor-default </value>
      <webElementGuid>bb086143-2b5f-46c4-8d2e-c78b79906801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-imgproxy.nccsoft.vn/_AEhOrrckkG-NjqIdVLtzc-dtLFuE4u6ClM0P46ICEY/rs:fit:600:300:1/plain/https://cdn.mezon.vn/stickers/7228675923802226677@png</value>
      <webElementGuid>85d24ad0-f085-4101-8f0d-258c1b384e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>30a1afea-08ca-4288-bb91-da3a1e29d2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-1840651252774473728&quot;)/div[@class=&quot;relative rounded-sm overflow-visible&quot;]/div[@class=&quot;flex h-15 flex-col w-auto px-3&quot;]/div[@class=&quot;justify-start gap-4 inline-flex w-full relative h-fit overflow-visible pr-12&quot;]/div[@class=&quot;w-full relative h-full&quot;]/div[@class=&quot;justify-start items-center  inline-flex w-full h-full pt-[2px] textChat select-text&quot;]/div[@class=&quot;flex flex-col whitespace-pre-wrap text-base w-full cursor-text&quot;]/div[@class=&quot;flex flex-row justify-start flex-wrap w-full gap-x-2&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;my-1&quot;]/div[@class=&quot;flex&quot;]/img[@class=&quot;flex object-cover object-left-top rounded cursor-default&quot;]</value>
      <webElementGuid>01ffbd5d-1961-48b8-a524-3059e2852f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg-1840651252774473728']/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>b54f276e-5004-4465-a662-31d24f7917e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='message'])[7]</value>
      <webElementGuid>6a544678-8f25-413a-9b2c-7bfee1d5878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>c6750ffb-afd7-4c93-b915-aa68008e242f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev-imgproxy.nccsoft.vn/_AEhOrrckkG-NjqIdVLtzc-dtLFuE4u6ClM0P46ICEY/rs:fit:600:300:1/plain/https://cdn.mezon.vn/stickers/7228675923802226677@png' and @alt = 'message']</value>
      <webElementGuid>b7108edb-8767-4003-9c1a-933384d23e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
