<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stickers</name>
   <tag></tag>
   <elementGuidId>a09de640-f96f-4911-b647-5798bf8113ff</elementGuidId>
   <imagePath>https://cdn.mezon.vn/sticker/FredTheDog/emojibest_com_fred_the_pug_1.gif</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>https://cdn.mezon.vn/sticker/FredTheDog/emojibest_com_fred_the_pug_1.gif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='grid grid-cols-3 gap-4 max-h-[400px] overflow-y-scroll hide-scrollbar']//img[@src='https://cdn.mezon.vn/sticker/FredTheDog/emojibest_com_fred_the_pug_1.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
